### ISSUE TITLE
Error start CSI

### ISSUE THREAD

**Issue by Dinidrol** [espressif/esp-csi#10]
IDF 4.3
![image](https://user-images.githubusercontent.com/17817431/114903074-177a5500-9e1f-11eb-9dec-815195022e59.png)

**Comment by zhanzhaocheng** [comment]
You need to enable the CSI function through `idf.py menuconfig`
```shell
idf.py menuconfig
Menu path: (Top) -> Component config -> Wi-Fi
```

![image](https://user-images.githubusercontent.com/19528396/117522333-54cc9f80-afe5-11eb-9212-c9fae4990b97.png)

**Comment by zhanzhaocheng** [comment]
Hello, @Dinidrol 

Closing this issue, feel free to reopen with more updates. Thanks.
