### ISSUE TITLE
Force AP to send frames in 802.11n (AEGHB-136)

### ISSUE THREAD

**Issue by hwawshy** [espressif/esp-csi#102]
Hi,

I have 2 esp32 chips, one acting as an AP and the other as a station connected to the AP. The station is a member of an IP-Multicast group. My laptop is also connected to the same esp32 AP. When I try to send a UDP packet to the address of the multicast group, the esp32 station receives the packet, but no CSI gets estimated. Upon investigating with Wireshark, I realized there are two packets in play, one from the laptop to the AP, which gets send at 802.11n rate, and another one from the AP to the multicast address, which gets send at  802.11b rate, which I assume is the reason why no CSI gets estimated at the station. Is there a way to force the AP to send the packet at PHY 802.11g/n  rates?

I tried using 

`    ESP_ERROR_CHECK(esp_wifi_set_protocol(WIFI_IF_AP, WIFI_PROTOCOL_11B|WIFI_PROTOCOL_11G|WIFI_PROTOCOL_11N));
    ESP_ERROR_CHECK(esp_wifi_config_11b_rate(WIFI_IF_AP, true));`
    
But it made the AP send the beacon frames in 802.11g (ERP) and it was a mess.

It's worth mentioning that when I run the csi_recv_router example with an esp32 as an AP, the ping responses get sent as 802.11g (ERP) and CSI works just fine.

**Comment by MacChu0315-Espressif** [comment]
Common settings can not force AP send frames at 802.11n rate, the transmitting rate may drop when the network environment is complex. 
Try to send frames by using ESP-NOW, it shall meet your requirements.

**Comment by zhanzhaocheng** [comment]
Hello, @hwawshy 

Closing this issue, feel free to reopen with more updates. Thanks.
