### ISSUE TITLE
CSI Data Specificaition (AEGHB-141)

### ISSUE THREAD

**Issue by zikunliu** [espressif/esp-csi#103]
I have a question about CSI data that received. What is the unit of imaginary and real part? why there are double-digit without decimal fraction. what is the meaning of imaginary and real part? What is the basis to calculate this two data part? Thanks in advance.

**Comment by MacChu0315-Espressif** [comment]
1. There is no unit for both imaginary and real part of CSI data.
2. For the data is sampled and quantified at the PHY.
3. CSI represents the change of the signal from a transmitter (denote it as x) to a receiver (denote it as y) and it is represented **in the frequency domain** as y = Hx + n, where H is a complex matrix consisting of CSI values and n is the
channel noise.
4. The CSI for each subcarrier is: h = |h|e jθ , where |h| represents the amplitude and θ the phase. #24 and #95 may help.

By the way, for detailed information, this paper _[Human Activity Recognition based on Wi-Fi CSI Data -A Deep Neural Network Approach](https://www.sciencedirect.com/science/article/pii/S1877050921024509)_ is recommended

**Comment by zhanzhaocheng** [comment]
Hello, @zikunliu

Closing this issue, feel free to reopen with more updates. Thanks.
