### ISSUE TITLE
你好，我想问一下ESP32有没有双天线的？采集两份CSI信息 (AEGHB-142)

### ISSUE THREAD

**Issue by xiangshang-kok** [espressif/esp-csi#104]
单天线在使用过程中，无法计算出相位差

**Comment by MacChu0315-Espressif** [comment]
Sadly, nope, we have no such a module that can receive wifi signal by using two antennas at the same time by now.
One way to calculate the phase difference of two devices is to make them share the same crystal oscillator.

**Comment by xiangshang-kok** [comment]
@MacChu0315-Espressif 
Thank you Sir, make them share the same crystal oscillator.Do you have any more specific operating methods?

**Comment by MacChu0315-Espressif** [comment]
@xiangshang-kok Sorry, detailed info is not available. Relative modules will be realeased in the future.

**Comment by zhanzhaocheng** [comment]
Hello, @xiangshang-kok 

Closing this issue, feel free to reopen with more updates. Thanks.

**Comment by kingaza** [comment]
> @xiangshang-kok Sorry, detailed info is not available. Relative modules will be realeased in the future.

@MacChu0315-Espressif when it will be released as plan?
