### ISSUE TITLE
No waveform_wander without training first (AEGHB-143)

### ISSUE THREAD

**Issue by karltamm** [espressif/esp-csi#105]
The function that I have assigned as `wifi_radar_cb` using `esp_radar_set_config()` doesn't receive `waveform_wander` (value is 0) without running `esp_radar_train_start()` first. However, the callback function receives `waveform_jitter` (greater than 0) even without previously calling `esp_radar_train_start()`.

```c
static void handle_wifi_radar_measurements(const wifi_radar_info_t* info, void* ctx) {
  ESP_LOGI(TAG, "Jitter: %f", info->waveform_jitter);
  ESP_LOGI(TAG, "Wander: %f", info->waveform_wander);
}
``` 

Is such behavior expected or should I look for a bug in my project?

**Comment by MacChu0315-Espressif** [comment]
Such behavior is expected. To measure whether "Wander" exists does not need advanced training. Training is a way to acquire a better threshold.

**Comment by xiangshang-kok** [comment]
@MacChu0315-Espressif 
Sir,I want to know `info->waveform_jitter`and `info->waveform_wander`，in which file these parameters calculated.I find in`app_main.c`and`radar_evaluate.c`and other files but noting get.

**Comment by karltamm** [comment]
@MacChu0315-Espressif
> To measure whether "Wander" exists does not need advanced training. Training is a way to acquire a better threshold.

As much as I understand [based on the example](https://github.com/espressif/esp-csi/blob/854fbe1517857a241533d7e989b7f56a8810d9b2/examples/console_test/main/app_main.c#L422), `waveform_wander` correlates with WiFi signal path loss because of human presence. If I boot up an ESP32, then I have to start with the training in order to measure `wander`. If at the same time people are in the same room and they interfere with the WiFi signal, then the acquired threshold is biased. In other words, I can't use the `waveform_wander` to accurately evaluate if people are in a room, because acquired threshold doesn't apply to a empty room.

Is my reasoning correct?

**Comment by MacChu0315-Espressif** [comment]
Sorry no one got back to you earlier. The calculation happens in libesp-csi.a and there are no plans to open source it for now. @xiangshang-kok

**Comment by MacChu0315-Espressif** [comment]
Sorry for the long delay in getting back to you and many thanks for being patient. Yes, your reasoning is correct. @karltamm
