### ISSUE TITLE
How do I find the sampling rate for the extraction of esp32, where on menuconfig? (AEGHB-152)

### ISSUE THREAD

**Issue by olliec28** [espressif/esp-csi#106]

**Comment by MacChu0315-Espressif** [comment]
What do you mean "sampling rate for the extraction of esp32", can you describe it in an other way?

**Comment by olliec28** [comment]
> What do you mean "sampling rate for the extraction of esp32", can you describe it in an other way?

I basically want to know what the sampling rate is, is it 100Hz, 10Hz? How do i find this out?

**Comment by MacChu0315-Espressif** [comment]
Therocally the sampling rate of ESP32 can reach millions per second.
The main bottleneck of sampling rate is sending rate, we used to sample CSI data at 3KHz.

**Comment by MacChu0315-Espressif** [comment]
Oh, i believe that i get you now, there was a misguide in what i said.

> Therocally the sampling rate of ESP32 can reach millions per second. The main bottleneck of sampling rate is sending rate, we used to sample CSI data at 3KHz.

I mean, therocally the sampling rate of ESP32 is millions per second. How many CSI data you receive per second mainly depend on the sending rate and how many frames you lose when transmitting.

**Comment by zhanzhaocheng** [comment]
Hello, @olliec28

Closing this issue, feel free to reopen with more updates. Thanks.
