### ISSUE TITLE
xiaomi router can't get CSI (AEGHB-155)

### ISSUE THREAD

**Issue by xiangshang-kok** [espressif/esp-csi#107]
when I run `console_test`,use esp32 chip with `csi_send` can get CSI ,but use xiaomi router as TX,can't get CSI. Log_data as follows 
\xfd\xffrestart
I (11807) system_cmd: Restarting
\x80\x80\x00\x80\x80\x00\x80\x80\x00\x80\x80\x80\x80\x80\x00\x00\x00\x80\x80\x80\x00\x80\x80\x80\x00\x80\x00\x80\x00\x80\x80\x00\x80\x80\x00\x80\x00\x80\x80\x00\x00\x00\x00\x00\x80\x00\x80\x80\x00\x00\x80\x80\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x80\x00\x00\x00\x00\x80\x00\x00\x00\x00\x00\x80\x80\x00\x80\x80\x00\x00\x80\x00\x00\x00\x80\x80\x80\x80\x80\x80\x00\x80\x80\x00\x80\x80\x00\x00\x80\x00\x80\x00\x80\x80\x00\x80\x80\x00\x80\x00\x00\x80\x00\x00\x00\x00\x00\x80\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x80\x00\x00\x80\x80\x00\x00\x80\x00\x00\x00\x80\x80\x00\x80\x00\x80\x80\x00\x80\x00\x00\x00\x00\x80\x80\x00\x80\x00\x00\x00\x80\x00\x00\x00\x80\x80\x00\x80\x80\x80\x80\x00\x80\x80\x80\x80\x80\x00\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x00\x80\x00\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x00\x00\x80\x80\x80\x00\x80\x80\x00\x80\x80\x80\x80\x00\x80\x00\x00\x80\x00\x00\x00\x80\x80\x80\x80\x80\x80\x80\x00\x80\x80\x00\x80\x00\x00\x00\x00\x80\x00\x00\x00\x00\x00\x80\x00\x80\x00\x80\x80\x00\x80\x80\x80\x00\x00\x80\x80\x80\x80\x00\x00\x80\x80\x00\x80\x80\x00\x80\x80\x00\x80\x80\x80\x80\x80\x80\x00\x00\x80\x00\x00\x80\x80\x00\x80\x80\x00\x80\x80\x00\x00\x80\x80\x80\x80\x00\x00\x80\x80\x00\x80\x80\x00\x80\x00\x80\x80\x80\x80\x00\x80\x00\x80\x80\x00\x00\x80\x00\x80\x00\x80\x80\x80\x00\x80\x00\x80\x80\x80\x80\x00\x80\x00\x00\x80\x00\x00\x00\x80\x80\x80\x00\x80\x00\x80\x00\x00\x00\x00\x80\x00\x80\x00\x00\x00\x80\x00\x00\x80\x80\x00\x80\x80\x80\x00\x80\x00\x80\x00\x00\x00\x00\x00\x80\x80\x00\x00\x80\x00\x80\x00\x80\x80\x00\x80\x80\x80\x00\x00\x80\x80\x80\x80\x80\x00\x80\x80\x00\x80\x00\x00\x00\x00\x80\x80\x80\x00\x80\x80\x80\x00\x80\x80\x80\x00\x00\x80\x00\x80\x80\x80\x80\x80\x80\x80\x00\x00\x80\x80\x80\x00\x80\x00\x80\x00\x00\x00\x80\x80\x00\x00\x80\x80\x00\x80\x00\x80\x00\x00\x00\x80\x00\x80\x00\x80\x80\x80\x80\x80\x80\x00\x80\x80\x80\x80\x80\x00\x00\x00\x00\x80\x80\x00\x80\x80\x00\x80\x80\x00\x80\x00\x80\x00\x00\x80\x80\x00\x00\x80\x00\x00\x80\x80\x80\x80\x80\x80\x00\x80\x00\x00\x80\x00\x80\x00\x00\x00\x00\x80\x80\x00\x00\x00\x00\x80\x80\x00\x80\x80\x80\x00\x80\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x80\x00\x00\x80\x80\x80\x80\x00\x80\x00\x80\x80\x00\x80\x00\x00\x00\x00\x80\x80\x00\x00\x80\x80\x00\x80\x00\x00\x80\x00\x80\x80\x80\x00\x00\x80\x00\x00\x80\x80\x80\x80\x80\x80\x00\x80\x00\x00\x80\x00\x80\x00\x00\x00\x00\x80\x00\x80\x00\x00\x00\x80\x00\x00\x80\x00\x80\x80\x00\x00\x80\x80\x00\x00\x00\x00\x00\x00\x80\x00\x00\x80\x80\x80\x80\x00\x80\x00\x80\x80\x00\x80\x00\x00\x00\x00\x80\x80\x80\x00\x80\x00\x00\x00\x80\x00\x80\x80\x00\x00\x80\x00\x00\x80\x80\x80\x80\x80\x80\x00\x80\x00\x00\x80\x00\x80\x00\x00\x00\x00\x80\x00\x80\x00\x00\x00\x80\x00\x00\x80\x00\x80\x80\x00\x80\x80\x80\x00\x00\x00\x00\x00\x00\x80\x00\x00\x80\x80\x80\x80\x00\x80\x00\x80\x80\x00\x80\x00\x00\x00\x00\x80\x80\x00\x00\x80\x00\x00\x00\x00\x00\x80\x00\x80\x80\x00\x00\x80\x00\x80\x80\x00\x80\x00\x80\x80\x00\x80\x80\x00\x00\x80\x80\x00\x80\x00\x00\x00\x00\x00\x80\x00\x80\x00\x00\x00\x80\x00\x00\x80\x00\x80\x80\x00\x00\x80\x00\x00\x00\x00\x00\x80\x00\x80\x80\x00\x00\x80\x00I (29) boot: ESP-IDF v4.4.4-340-g4c7d97e2bd-dirty 2nd stage bootloader
I (29) boot: compile time 18:37:03
I (29) boot: chip revision: v0.1
I (29) qio_mode: Enabling default flash chip QIO
I (30) boot.esp32s3: Boot SPI Speed : 80MHz
I (31) boot.esp32s3: SPI Mode       : QIO
I (31) boot.esp32s3: SPI Flash Size : 4MB
I (32) boot: Enabling RNG early entropy source...
I (33) boot: Partition Table:
I (33) boot: ## Label            Usage          Type ST Offset   Length
I (34) boot:  0 nvs              WiFi data        01 02 0000d000 00008000
I (35) boot:  1 fctry            WiFi data        01 02 00015000 00004000
I (36) boot:  2 log_status       WiFi data        01 02 00019000 00004000
I (37) boot:  3 otadata          OTA data         01 00 0001d000 00002000
I (38) boot:  4 phy_init         RF data          01 01 0001f000 00001000
I (39) boot:  5 ota_0            OTA app          00 10 00020000 001ca000
I (40) boot: End of partition table
I (40) esp_image: segment 0: paddr=00020020 vaddr=3c090020 size=18a64h (100964) map
I (56) esp_image: segment 1: paddr=00038a8c vaddr=3fc96ff0 size=03bech ( 15340) load
I (60) esp_image: segment 2: paddr=0003c680 vaddr=40374000 size=03998h ( 14744) load
I (63) esp_image: segment 3: paddr=00040020 vaddr=42000020 size=81ef4h (532212) map
I (144) esp_image: segment 4: paddr=000c1f1c vaddr=40377998 size=0f658h ( 63064) load
I (163) boot: Loaded app from partition at offset 0x20000
I (164) boot: Disabling RNG early entropy source...
I (165) cpu_start: Pro cpu up.
I (165) cpu_start: Starting app cpu, entry point is 0x403753a0
I (144) cpu_start: App cpu up.
I (174) cpu_start: Pro cpu start user code
I (174) cpu_start: cpu freq: 240000000
I (174) cpu_start: Application information:
I (174) cpu_start: Project name:     new_console_test
I (175) cpu_start: App version:      854fbe1-dirty
I (176) cpu_start: Compile time:     Apr 18 2023 18:37:00
I (177) cpu_start: ELF file SHA256:  2016e724649f949c...
I (177) cpu_start: ESP-IDF:          v4.4.4-340-g4c7d97e2bd-dirty
I (178) cpu_start: Min chip rev:     v0.0
I (179) cpu_start: Max chip rev:     v0.99 
I (179) cpu_start: Chip rev:         v0.1
I (180) heap_init: Initializing. RAM available for dynamic allocation:
I (181) heap_init: At 3FC9EFA0 len 0004A770 (297 KiB): D/IRAM
I (182) heap_init: At 3FCE9710 len 00005724 (21 KiB): STACK/DIRAM
I (182) heap_init: At 3FCF0000 len 00008000 (32 KiB): DRAM
I (183) heap_init: At 600FE000 len 00002000 (8 KiB): RTCRAM
I (184) spi_flash: detected chip: gd
I (185) spi_flash: flash io: qio
W (185) spi_flash: Detected size(16384k) larger than the size in the binary image header(4096k). Using the size in the binary image header.
I (187) sleep: Configure to isolate all GPIO pins in sleep state
I (188) sleep: Enable automatic switching of GPIO sleep configuration
I (189) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
\x1b[5
"Type 'help' to get the list of commands.\r\r\n"
Use UP/DOWN arrows to navigate through command history.
Press TAB when typing command name to auto-complete.
Your terminal application does not support escape sequences.
Line editing and history features are disabled.
On Windows, try using Putty instead.
csi> I (615) pp: pp rom version: e7ae62f
I (616) net80211: net80211 rom version: e7ae62f
I (618) wifi:wifi driver task: 3fceebc4, prio:23, stack:6656, core=0
I (618) system_api: Base MAC address is not set
I (619) system_api: read default base MAC address from EFUSE
I (621) wifi:wifi firmware version: 594be7d
I (622) wifi:wifi certification version: v7.0
I (622) wifi:config NVS flash: enabled
I (623) wifi:config nano formating: disabled
I (623) wifi:Init data frame dynamic rx buffer num: 32
I (624) wifi:Init management frame dynamic rx buffer num: 32
I (625) wifi:Init management short buffer num: 32
I (625) wifi:Init dynamic tx buffer num: 32
I (626) wifi:Init static tx FG buffer num: 2
I (626) wifi:Init static rx buffer size: 2212
I (627) wifi:Init static rx buffer num: 10
I (627) wifi:Init dynamic rx buffer num: 32
I (628) wifi_init: tcpip mbox: 32
I (629) wifi_init: udp mbox: 6
I (629) wifi_init: tcp mbox: 6
I (630) wifi_init: tcp tx win: 5744
I (630) wifi_init: tcp rx win: 5744
I (631) wifi_init: tcp mss: 1440
I (631) wifi_init: WiFi IRAM OP enabled
I (632) wifi_init: WiFi RX IRAM OP enabled
I (633) phy_init: phy_version 540,a5d905b,Oct 20 2022,19:36:11
I (665) wifi:mode : null
I (666) wifi:Set ps type: 0
I (667) wifi:ic_enable_sniffe
I (667) esp_radar: CSI_RADAR Version: 0.0.7, Compile time: Dec  9 2022 - 17:22:21
I (668) esp_radar: csi_recv_interval: 10, csi_handle_time: 250, csi_handle_window: 50, csi_handle_buffer: 60
radar --csi_output_type LLFT --csi_output_format base64
csi> 
csi> 
wifi_config --ssid CSI_AP --password 1234560.
I (4301) wifi:mode : sta (f4:12:fa:e7:a0:70)
I (4302) wifi:enable tsf
I (4312) wifi:new:<1,0>, old:<11,2>, ap:<255,255>, sta:<1,0>, prof:1
I (4991) wifi:state: init -> auth (b0)
I (5028) wifi:state: auth -> assoc (0)
I (5097) wifi:state: assoc -> run (10)
I (5231) wifi:connected with CSI_AP, aid = 1, channel 1, BW20, bssid = ec:41:18:e0:00:ba
I (5232) wifi:security: WPA2-PSK, phy: bgn, rssi: -71
I (5233) wifi:pm start, type: 0
I (5234) wifi:set rx beacon pti, rx_bcn_pti: 0, bcn_timeout: 0, mt_pti: 25000, mt_time: 10000
I (5235) wifi_cmd: Connected to CSI_AP (bssid: ec:41:18:e0:00:ba, channel: 1)
"I (5260) wifi:AP's beacon interval = 102400 us, DTIM period = 1\r\n"
I (6738) ping_cmd: ping router ip:192.168.31.217, gw: 192.168.31.1
I (6740) wifi:ic_disable_sniffe
I (6740) esp_netif_handlers: sta ip: 192.168.31.217, mask: 255.255.255.0, gw: 192.168.31.1
csi> 
csi> I (6744) radar_evaluate: Socket created
I (6745) radar_evaluate: Socket bound, port 3232
I (6746) radar_evaluate: Socket listening
W (35952) ping_cmd: From 192.168.31.1 icmp_seq=2822 timeout
W (44102) ping_cmd: From 192.168.31.1 icmp_seq=3637 timeout
W (59086) ping_cmd: From 192.168.31.1 icmp_seq=5135 timeout
W (72354) ping_cmd: From 192.168.31.1 icmp_seq=6462 timeout
W (103402) ping_cmd: From 192.168.31.1 icmp_seq=9567 timeout
ping --abort
W (138014) ping_cmd: esp_ping stop
csi> 
csi> wifi_config --disconnect
I (138017) wifi:state: run -> init (0)
I (138018) wifi:pm stop, total sleep time: 0 us / 132784613 us
I (138019) wifi:new:<1,0>, old:<1,0>, ap:<255,255>, sta:<1,0>, prof:1
csi> 
csi> 
W (139012) ping_cmd: From 192.168.31.1 icmp_seq=13128 timeout
I (139014) ping_cmd: 
--- 192.168.31.1 ping statistics ---
I (139015) ping_cmd: 13128 packets transmitted, 13122 received, 0% packet loss, time 48891ms

~~~~~~~~~
whether not all router can get CSI ?

**Comment by zhanzhaocheng** [comment]
Hello, @xiangshang-kok 

Closing this issue, feel free to reopen with more updates. Thanks.
