### ISSUE TITLE
Do you have plans for releasing source for `libesp-csi.a`? (AEGHB-157)

### ISSUE THREAD

**Issue by jayavanth** [espressif/esp-csi#108]

**Comment by xiangshang-kok** [comment]
Sir,I would like to know what info content in the `libesp-csi.a` file

I am finding the `info->waveform_wander`parameter,how does it calculate，but noting found.Do you have any suggestion?

**Comment by YunduanBeichen** [comment]
Similarly, in other issues, I found that the project can be run on esp32s2. But in actual operation, the libesp-csi.a file is missing in the lib folder. Could you please provide it?

**Comment by MacChu0315-Espressif** [comment]
I am sorry that there are no plans to open source the libesp-csi.a for now.

**Comment by MacChu0315-Espressif** [comment]
@YunduanBeichen Sorry no one got back to you earlier. If nothing important changed have been made, you can try to run the command `git checkout master` and `git reset --hard` to get the missing file.

**Comment by zhanzhaocheng** [comment]
Hello, @jayavanth 

Closing this issue, feel free to reopen with more updates. Thanks.

**Comment by jayavanth** [comment]
Does `libesp-csi.a` also have Apache-2.0 as license? Can I use it commercially?

**Comment by zhanzhaocheng** [comment]
@jayavanth libesp-csi.a is also Apache-2.0 and you can use it commercially
