### ISSUE TITLE
Continuous detective CSI In a particular channel

### ISSUE THREAD

**Issue by zhangyang428** [espressif/esp-csi#11]
1) I don't use ping commanda and i get the CSI for the specific channel with the code you provide. But filtering sometimes fails, 
I often get CSI data from other devices. Is there any way to solve this?
2)  I do an FTM data exchange on the channel 1, but no CSI data is generated on the same channel. Do you know why? Or do you have any good suggestions?

Thank you!

**Comment by zhanzhaocheng** [comment]
1. You can filter the CSI information of other devices by mac address
2. Only after reclaiming 802.11 g/n data packets, will the CSI be returned to the application layer.

**Comment by zhanzhaocheng** [comment]
Hello, @zhangyang428 

Closing this issue, feel free to reopen with more updates. Thanks.
