### ISSUE TITLE
CSI receiver blocked (AEGHB-164)

### ISSUE THREAD

**Issue by HKSIWAR** [espressif/esp-csi#110]
Hi all,
I flashed two esp32 the first one is sender and the source code is in the following path :
https://github.com/espressif/esp-csi/tree/master/examples/get-started/csi_send
and the second is receiver and here is their path:
https://github.com/espressif/esp-csi/tree/master/examples/console_test
After 1 hour and 30 minutes, the sender works fine but the serial monitor of the receiver has been blocked, in fact the console does not display new data as shown in the following figure:
![monitor](https://user-images.githubusercontent.com/128044470/235107697-415eab47-a815-48fa-9a16-864d7ca38181.png)

I have done this experience a few times and we always have the same problem.
What is the reason for this problem?

**Comment by ahmed123-sys** [comment]
I have the same issue. Any suggestions!

**Comment by MacChu0315-Espressif** [comment]
Thanks for discovering and reporting this problem. we have reproduced the problem and now is working on it.

**Comment by zhanzhaocheng** [comment]
@ahmed123-sys This issue has been fixed, please update and verify it
