### ISSUE TITLE
Threshold calibration principle (AEGHB-169)

### ISSUE THREAD

**Issue by xiaokangkang6** [espressif/esp-csi#112]
Could you briefly describe the principle of automatic threshold calibration?

**Comment by MacChu0315-Espressif** [comment]
You mean the threshold calibration of judging whether wander or jitter exists? If so, i am sorry that it is not open source by now.

**Comment by zhanzhaocheng** [comment]
Hello, @xiaokangkang6 

Closing this issue, feel free to reopen with more updates. Thanks.
