### ISSUE TITLE
License type of WiFI CSI (AEGHB-176)

### ISSUE THREAD

**Issue by smtibaa** [espressif/esp-csi#113]
I would like to have an idea about license type of your Wi-FI CSI projet including the detection algorithm.
My question is just to check if there are any limitations to commercialize smart plugs ESP32 based with this module ? 

Thanks,
Sabri

**Comment by zhanzhaocheng** [comment]
Hello, @smtibaa 

Closing this issue, feel free to reopen with more updates. Thanks.
