### ISSUE TITLE
connect_qcloud 编译不过（配合moonlight开发板）

### ISSUE THREAD

**Issue by cuityanxi** [espressif/esp-csi#12]
[101/101] Generating binary image from built executable
esptool.py v3.0
Generated D:/ESP/esp-idf/examples/esp-csi-master/examples/connect_qcloud/build/bootloader/bootloader.bin
[1188/1202] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/light_driver.c.obj
FAILED: esp-idf/main/CMakeFiles/__idf_main.dir/light_driver.c.obj
ccache D:\ESP\.espressif\tools\xtensa-esp32-elf\esp-2020r3-8.4.0\xtensa-esp32-elf\bin\xtensa-esp32-elf-gcc.exe -DHAVE_CONFIG_H -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -DUNITY_INCLUDE_CONFIG_H -DWITH_POSIX -Iconfig -I../main -I../../../../../components/newlib/platform_include -I../../../../../components/freertos/include -I../../../../../components/freertos/xtensa/include -I../../../../../components/heap/include -I../../../../../components/log/include -I../../../../../components/lwip/include/apps -I../../../../../components/lwip/include/apps/sntp -I../../../../../components/lwip/lwip/src/include -I../../../../../components/lwip/port/esp32/include -I../../../../../components/lwip/port/esp32/include/arch -I../../../../../components/soc/src/esp32/. -I../../../../../components/soc/src/esp32/include -I../../../../../components/soc/include -I../../../../../components/esp_rom/include -I../../../../../components/esp_common/include -I../../../../../components/esp_system/include -I../../../../../components/xtensa/include -I../../../../../components/xtensa/esp32/include -I../../../../../components/esp32/include -I../../../../../components/driver/include -I../../../../../components/driver/esp32/include -I../../../../../components/esp_ringbuf/include -I../../../../../components/efuse/include -I../../../../../components/efuse/esp32/include -I../../../../../components/espcoredump/include -I../../../../../components/esp_timer/include -I../../../../../components/esp_ipc/include -I../../../../../components/soc/soc/esp32/include -I../../../../../components/soc/soc/esp32/../include -I../../../../../components/soc/soc/esp32/private_include -I../../../../../components/vfs/include -I../../../../../components/esp_wifi/include -I../../../../../components/esp_wifi/esp32/include -I../../../../../components/esp_event/include -I../../../../../components/esp_netif/include -I../../../../../components/esp_eth/include -I../../../../../components/tcpip_adapter/include -I../../../../../components/app_trace/include -I../../../../../components/mbedtls/port/include -I../../../../../components/mbedtls/mbedtls/include -I../../../../../components/mbedtls/esp_crt_bundle/include -I../../../../../components/bootloader_support/include -I../../../../../components/app_update/include -I../../../../../components/spi_flash/include -I../../../../../components/wpa_supplicant/include -I../../../../../components/wpa_supplicant/port/include -I../../../../../components/wpa_supplicant/include/esp_supplicant -I../../../../../components/nvs_flash/include -I../../../../../components/pthread/include -I../../../../../components/perfmon/include -I../../../../../components/asio/asio/asio/include -I../../../../../components/asio/port/include -I../../../../../components/bt/include -I../../../../../components/bt/common/osi/include -I../../../../../components/bt/host/bluedroid/api/include/api -I../../../../../components/cbor/port/include -I../../../../../components/coap/port/include -I../../../../../components/coap/port/include/coap -I../../../../../components/coap/libcoap/include -I../../../../../components/coap/libcoap/include/coap2 -I../../../../../components/console -I../../../../../components/nghttp/port/include -I../../../../../components/nghttp/nghttp2/lib/includes -I../../../../../components/esp-tls -I../../../../../components/esp_adc_cal/include -I../../../../../components/esp_gdbstub/include -I../../../../../components/esp_hid/include -I../../../../../components/tcp_transport/include -I../../../../../components/esp_http_client/include -I../../../../../components/esp_http_server/include -I../../../../../components/esp_https_ota/include -I../../../../../components/protobuf-c/protobuf-c -I../../../../../components/protocomm/include/common -I../../../../../components/protocomm/include/security -I../../../../../components/protocomm/include/transports -I../../../../../components/mdns/include -I../../../../../components/esp_local_ctrl/include -I../../../../../components/sdmmc/include -I../../../../../components/esp_serial_slave_link/include -I../../../../../components/esp_websocket_client/include -I../../../../../components/expat/expat/expat/lib -I../../../../../components/expat/port/include -I../../../../../components/wear_levelling/include -I../../../../../components/fatfs/diskio -I../../../../../components/fatfs/vfs -I../../../../../components/fatfs/src -I../../../../../components/freemodbus/common/include -I../../../../../components/idf_test/include -I../../../../../components/idf_test/include/esp32 -I../../../../../components/jsmn/include -I../../../../../components/json/cJSON -I../../../../../components/libsodium/libsodium/src/libsodium/include -I../../../../../components/libsodium/port_include -I../../../../../components/mqtt/esp-mqtt/include -I../../../../../components/openssl/include -I../../../../../components/spiffs/include -I../../../../../components/ulp/include -I../../../../../components/unity/include -I../../../../../components/unity/unity/src -I../../../../../components/wifi_provisioning/include -I../../../include -I../../../../system/console/components/cmd_nvs -I../../../../system/console/components/cmd_system -mlongcalls -Wno-frame-address   -fdiagnostics-color=always -ffunction-sections -fdata-sections -fstrict-volatile-bitfields -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-but-set-variable -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -ggdb -Og -std=gnu99 -Wno-old-style-declaration -D_GNU_SOURCE -DIDF_VER=\"v4.2-dirty\" -DESP_PLATFORM -MD -MT esp-idf/main/CMakeFiles/__idf_main.dir/light_driver.c.obj -MF esp-idf\main\CMakeFiles\__idf_main.dir\light_driver.c.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir/light_driver.c.obj   -c ../main/light_driver.c
../main/light_driver.c:26:10: fatal error: led_pwm.h: No such file or directory
 #include "led_pwm.h"
          ^~~~~~~~~~~
compilation terminated.
[1190/1202] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/qcloud_light.c.obj
FAILED: esp-idf/main/CMakeFiles/__idf_main.dir/qcloud_light.c.obj
ccache D:\ESP\.espressif\tools\xtensa-esp32-elf\esp-2020r3-8.4.0\xtensa-esp32-elf\bin\xtensa-esp32-elf-gcc.exe -DHAVE_CONFIG_H -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -DUNITY_INCLUDE_CONFIG_H -DWITH_POSIX -Iconfig -I../main -I../../../../../components/newlib/platform_include -I../../../../../components/freertos/include -I../../../../../components/freertos/xtensa/include -I../../../../../components/heap/include -I../../../../../components/log/include -I../../../../../components/lwip/include/apps -I../../../../../components/lwip/include/apps/sntp -I../../../../../components/lwip/lwip/src/include -I../../../../../components/lwip/port/esp32/include -I../../../../../components/lwip/port/esp32/include/arch -I../../../../../components/soc/src/esp32/. -I../../../../../components/soc/src/esp32/include -I../../../../../components/soc/include -I../../../../../components/esp_rom/include -I../../../../../components/esp_common/include -I../../../../../components/esp_system/include -I../../../../../components/xtensa/include -I../../../../../components/xtensa/esp32/include -I../../../../../components/esp32/include -I../../../../../components/driver/include -I../../../../../components/driver/esp32/include -I../../../../../components/esp_ringbuf/include -I../../../../../components/efuse/include -I../../../../../components/efuse/esp32/include -I../../../../../components/espcoredump/include -I../../../../../components/esp_timer/include -I../../../../../components/esp_ipc/include -I../../../../../components/soc/soc/esp32/include -I../../../../../components/soc/soc/esp32/../include -I../../../../../components/soc/soc/esp32/private_include -I../../../../../components/vfs/include -I../../../../../components/esp_wifi/include -I../../../../../components/esp_wifi/esp32/include -I../../../../../components/esp_event/include -I../../../../../components/esp_netif/include -I../../../../../components/esp_eth/include -I../../../../../components/tcpip_adapter/include -I../../../../../components/app_trace/include -I../../../../../components/mbedtls/port/include -I../../../../../components/mbedtls/mbedtls/include -I../../../../../components/mbedtls/esp_crt_bundle/include -I../../../../../components/bootloader_support/include -I../../../../../components/app_update/include -I../../../../../components/spi_flash/include -I../../../../../components/wpa_supplicant/include -I../../../../../components/wpa_supplicant/port/include -I../../../../../components/wpa_supplicant/include/esp_supplicant -I../../../../../components/nvs_flash/include -I../../../../../components/pthread/include -I../../../../../components/perfmon/include -I../../../../../components/asio/asio/asio/include -I../../../../../components/asio/port/include -I../../../../../components/bt/include -I../../../../../components/bt/common/osi/include -I../../../../../components/bt/host/bluedroid/api/include/api -I../../../../../components/cbor/port/include -I../../../../../components/coap/port/include -I../../../../../components/coap/port/include/coap -I../../../../../components/coap/libcoap/include -I../../../../../components/coap/libcoap/include/coap2 -I../../../../../components/console -I../../../../../components/nghttp/port/include -I../../../../../components/nghttp/nghttp2/lib/includes -I../../../../../components/esp-tls -I../../../../../components/esp_adc_cal/include -I../../../../../components/esp_gdbstub/include -I../../../../../components/esp_hid/include -I../../../../../components/tcp_transport/include -I../../../../../components/esp_http_client/include -I../../../../../components/esp_http_server/include -I../../../../../components/esp_https_ota/include -I../../../../../components/protobuf-c/protobuf-c -I../../../../../components/protocomm/include/common -I../../../../../components/protocomm/include/security -I../../../../../components/protocomm/include/transports -I../../../../../components/mdns/include -I../../../../../components/esp_local_ctrl/include -I../../../../../components/sdmmc/include -I../../../../../components/esp_serial_slave_link/include -I../../../../../components/esp_websocket_client/include -I../../../../../components/expat/expat/expat/lib -I../../../../../components/expat/port/include -I../../../../../components/wear_levelling/include -I../../../../../components/fatfs/diskio -I../../../../../components/fatfs/vfs -I../../../../../components/fatfs/src -I../../../../../components/freemodbus/common/include -I../../../../../components/idf_test/include -I../../../../../components/idf_test/include/esp32 -I../../../../../components/jsmn/include -I../../../../../components/json/cJSON -I../../../../../components/libsodium/libsodium/src/libsodium/include -I../../../../../components/libsodium/port_include -I../../../../../components/mqtt/esp-mqtt/include -I../../../../../components/openssl/include -I../../../../../components/spiffs/include -I../../../../../components/ulp/include -I../../../../../components/unity/include -I../../../../../components/unity/unity/src -I../../../../../components/wifi_provisioning/include -I../../../include -I../../../../system/console/components/cmd_nvs -I../../../../system/console/components/cmd_system -mlongcalls -Wno-frame-address   -fdiagnostics-color=always -ffunction-sections -fdata-sections -fstrict-volatile-bitfields -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-but-set-variable -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -ggdb -Og -std=gnu99 -Wno-old-style-declaration -D_GNU_SOURCE -DIDF_VER=\"v4.2-dirty\" -DESP_PLATFORM -MD -MT esp-idf/main/CMakeFiles/__idf_main.dir/qcloud_light.c.obj -MF esp-idf\main\CMakeFiles\__idf_main.dir\qcloud_light.c.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir/qcloud_light.c.obj   -c ../main/qcloud_light.c
../main/qcloud_light.c:14:10: fatal error: esp_qcloud_log.h: No such file or directory
 #include "esp_qcloud_log.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
[1191/1202] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/app_main.c.obj
FAILED: esp-idf/main/CMakeFiles/__idf_main.dir/app_main.c.obj
ccache D:\ESP\.espressif\tools\xtensa-esp32-elf\esp-2020r3-8.4.0\xtensa-esp32-elf\bin\xtensa-esp32-elf-gcc.exe -DHAVE_CONFIG_H -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -DUNITY_INCLUDE_CONFIG_H -DWITH_POSIX -Iconfig -I../main -I../../../../../components/newlib/platform_include -I../../../../../components/freertos/include -I../../../../../components/freertos/xtensa/include -I../../../../../components/heap/include -I../../../../../components/log/include -I../../../../../components/lwip/include/apps -I../../../../../components/lwip/include/apps/sntp -I../../../../../components/lwip/lwip/src/include -I../../../../../components/lwip/port/esp32/include -I../../../../../components/lwip/port/esp32/include/arch -I../../../../../components/soc/src/esp32/. -I../../../../../components/soc/src/esp32/include -I../../../../../components/soc/include -I../../../../../components/esp_rom/include -I../../../../../components/esp_common/include -I../../../../../components/esp_system/include -I../../../../../components/xtensa/include -I../../../../../components/xtensa/esp32/include -I../../../../../components/esp32/include -I../../../../../components/driver/include -I../../../../../components/driver/esp32/include -I../../../../../components/esp_ringbuf/include -I../../../../../components/efuse/include -I../../../../../components/efuse/esp32/include -I../../../../../components/espcoredump/include -I../../../../../components/esp_timer/include -I../../../../../components/esp_ipc/include -I../../../../../components/soc/soc/esp32/include -I../../../../../components/soc/soc/esp32/../include -I../../../../../components/soc/soc/esp32/private_include -I../../../../../components/vfs/include -I../../../../../components/esp_wifi/include -I../../../../../components/esp_wifi/esp32/include -I../../../../../components/esp_event/include -I../../../../../components/esp_netif/include -I../../../../../components/esp_eth/include -I../../../../../components/tcpip_adapter/include -I../../../../../components/app_trace/include -I../../../../../components/mbedtls/port/include -I../../../../../components/mbedtls/mbedtls/include -I../../../../../components/mbedtls/esp_crt_bundle/include -I../../../../../components/bootloader_support/include -I../../../../../components/app_update/include -I../../../../../components/spi_flash/include -I../../../../../components/wpa_supplicant/include -I../../../../../components/wpa_supplicant/port/include -I../../../../../components/wpa_supplicant/include/esp_supplicant -I../../../../../components/nvs_flash/include -I../../../../../components/pthread/include -I../../../../../components/perfmon/include -I../../../../../components/asio/asio/asio/include -I../../../../../components/asio/port/include -I../../../../../components/bt/include -I../../../../../components/bt/common/osi/include -I../../../../../components/bt/host/bluedroid/api/include/api -I../../../../../components/cbor/port/include -I../../../../../components/coap/port/include -I../../../../../components/coap/port/include/coap -I../../../../../components/coap/libcoap/include -I../../../../../components/coap/libcoap/include/coap2 -I../../../../../components/console -I../../../../../components/nghttp/port/include -I../../../../../components/nghttp/nghttp2/lib/includes -I../../../../../components/esp-tls -I../../../../../components/esp_adc_cal/include -I../../../../../components/esp_gdbstub/include -I../../../../../components/esp_hid/include -I../../../../../components/tcp_transport/include -I../../../../../components/esp_http_client/include -I../../../../../components/esp_http_server/include -I../../../../../components/esp_https_ota/include -I../../../../../components/protobuf-c/protobuf-c -I../../../../../components/protocomm/include/common -I../../../../../components/protocomm/include/security -I../../../../../components/protocomm/include/transports -I../../../../../components/mdns/include -I../../../../../components/esp_local_ctrl/include -I../../../../../components/sdmmc/include -I../../../../../components/esp_serial_slave_link/include -I../../../../../components/esp_websocket_client/include -I../../../../../components/expat/expat/expat/lib -I../../../../../components/expat/port/include -I../../../../../components/wear_levelling/include -I../../../../../components/fatfs/diskio -I../../../../../components/fatfs/vfs -I../../../../../components/fatfs/src -I../../../../../components/freemodbus/common/include -I../../../../../components/idf_test/include -I../../../../../components/idf_test/include/esp32 -I../../../../../components/jsmn/include -I../../../../../components/json/cJSON -I../../../../../components/libsodium/libsodium/src/libsodium/include -I../../../../../components/libsodium/port_include -I../../../../../components/mqtt/esp-mqtt/include -I../../../../../components/openssl/include -I../../../../../components/spiffs/include -I../../../../../components/ulp/include -I../../../../../components/unity/include -I../../../../../components/unity/unity/src -I../../../../../components/wifi_provisioning/include -I../../../include -I../../../../system/console/components/cmd_nvs -I../../../../system/console/components/cmd_system -mlongcalls -Wno-frame-address   -fdiagnostics-color=always -ffunction-sections -fdata-sections -fstrict-volatile-bitfields -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-but-set-variable -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -ggdb -Og -std=gnu99 -Wno-old-style-declaration -D_GNU_SOURCE -DIDF_VER=\"v4.2-dirty\" -DESP_PLATFORM -MD -MT esp-idf/main/CMakeFiles/__idf_main.dir/app_main.c.obj -MF esp-idf\main\CMakeFiles\__idf_main.dir\app_main.c.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir/app_main.c.obj   -c ../main/app_main.c
In file included from ../main/app_main.c:31:
../main/qcloud_light.h:13:10: fatal error: esp_qcloud_log.h: No such file or directory
 #include "esp_qcloud_log.h"
          ^~~~~~~~~~~~~~~~~~

**Comment by zztiger123** [comment]
您好, ESP-CSI 需要在特定的 idf 版本上运行， commit 为 6e776946d01ec0d081d09000c36d23ec1d318c06。你需要 `git checkout 6e776946d01ec0d081d09000c36d23ec1d318c06` 来切换到指定的 idf 版本。

**Comment by cuityanxi** [comment]
esp-idf-tools-setup-2.3 安装的master，如何切过去呢

**Comment by Jiangyafeng** [comment]
@cuityanxi 建议您切换到linux下 去开发，你这个工具链太老了，是不支持的。

**Comment by cuityanxi** [comment]
../main/qcloud_light.h:13:10: fatal error: esp_qcloud_log.h: No such file or directory
 #include "esp_qcloud_log.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
ninja failed with exit code 1
jiangyanxi@GMPC2020050018:~/esp/esp-idf/examples/wifi/csi/esp-csi/examples/connect_qcloud$ 
jiangyanxi@GMPC2020050018:~/esp/esp-idf/examples/wifi/csi/esp-csi/examples/connect_qcloud$ 
jiangyanxi@GMPC2020050018:~/esp/esp-idf/examples/wifi/csi/esp-csi/examples/connect_qcloud$ cd ..
jiangyanxi@GMPC2020050018:~/esp/esp-idf/examples/wifi/csi/esp-csi/examples$ cd ..
jiangyanxi@GMPC2020050018:~/esp/esp-idf/examples/wifi/csi/esp-csi$ cd ..
jiangyanxi@GMPC2020050018:~/esp/esp-idf/examples/wifi/csi$ cd ..
jiangyanxi@GMPC2020050018:~/esp/esp-idf/examples/wifi$ cd ..
jiangyanxi@GMPC2020050018:~/esp/esp-idf/examples$ cd ..
jiangyanxi@GMPC2020050018:~/esp/esp-idf$ git show
commit 6e776946d01ec0d081d09000c36d23ec1d318c06 (HEAD, develop)
Merge: c4346abfb d34acd0d8
Author: Mahavir Jain <mahavir@espressif.com>
Date:   Mon Feb 1 13:22:30 2021 +0800

    Merge branch 'bugfix/update_howsmyssl_cert' into 'master'
    
    examples/protocols: update www.howsmyssl.com certificate to fix test failures
    
    See merge request espressif/esp-idf!12202


还是有问题呢？

**Comment by cuityanxi** [comment]
以解决
