### ISSUE TITLE
Error running `csi_data_read_parse.py` (AEGHB-259)

### ISSUE THREAD

**Issue by ge419** [espressif/esp-csi#122]
I was trying to run `csi_data_read_parse.py` using 2 ESP32-S3-WROOM-2 (one flashed with csi_recv and the other with csi_send) and these messages multiple times in the terminal:

`element number is not equal`
`data is incomplete`

As instructed in the [README.md](https://github.com/espressif/esp-csi/blob/master/examples/get-started/README.md), I tried higher baud rates to avoid this issue, but I still get these messages. Is there another way to avoid this error?

**Comment by MacChu0315-Espressif** [comment]
Sorry, I couldn't successfully reproduce your problem. Is the information you mentioned appearing all the time or occasionally? The default baud rate is 961200, but it can be increased to 2MHz, you can also try it. Please feel free to let us know if you have any further questions or need further support.

**Comment by zhanzhaocheng** [comment]
Hello, @ge419 

Closing this issue, feel free to reopen with more updates. Thanks.
