### ISSUE TITLE
CSI in sniffer mode (AEGHB-278)

### ISSUE THREAD

**Issue by nicosacco** [espressif/esp-csi#124]
Hi! I have a couple of questions about CSI in sniffer mode.

I developed and app running in a ESP32-S3 that catches CSI packets by means of the esp-idf callback. Currently the board is set to operate in the WIFI_MODE_NULL with promiscuous mode enabled. The idea is that of gathering all the "CSI packets over the air", as the board is not connect to any AP, and no devices are connected to the board.

From my understanding about how CSI is computed, it is determined at the receiver from some OFDM symbols in the preamble of the packet sent by the transmitter (let's stick to the L-LTF 1x1 20Mhz case). In my setting, of course, a received packet was not addressed to the board. Thus, is the CSI information I am getting from it still describing correctly the channel between my board and the transmitting AP, or it is conveying information pertaining to the AP and the device to which the packet was addressed? My understanding is that the information conveyed is about the board and the AP, since the transmitted symbols should be pre-defined (right?). Moreover, could the board be getting CSI information also from packets sent by other devices that are not APs?

Thanks!

**Comment by zhanzhaocheng** [comment]
You can think of CSI in terms of RSSI, where CSI is the physical information and RSSI is the data link layer information. A device with promiscuous mode can receive RSSI information from other devices, so it can also receive CSI information. CSI reflects the network situation between other devices and the current device just like RSSI

**Comment by zhanzhaocheng** [comment]
Hello, @nicosacco 

Closing this issue, feel free to reopen with more updates. Thanks.
