### ISSUE TITLE
不断重启

### ISSUE THREAD

**Issue by cuityanxi** [espressif/esp-csi#14]
I (577) heap_init: At 40078000 len 00008000 (32 KiB): IRAM
I (583) heap_init: At 40096E48 len 000091B8 (36 KiB): IRAM
I (589) spi_flash: detected chip: generic
I (594) spi_flash: flash io: qio
I (598) esp_core_dump_flash: Init core dump to flash
I (604) esp_core_dump_flash: Found partition 'coredump' @ 3c0000 65536 bytes
I (617) esp_core_dump_flash: Core dump data checksum is correct
I (618) esp_core_dump_flash: Found core dump 8452 bytes in flash @ 0x3c0000
I (626) cpu_start: Starting scheduler on PRO CPU.
D (643) esp_qcloud_reboot: reboot unbroken count: 1
D (646) esp_qcloud_reboot: version_fallback_task exit
W (647) esp_qcloud_log_flash: <ESP_ERR_NVS_NOT_FOUND> NVS open for log_status log_info log_info failed
I (782) esp_qcloud_log_flash: LOG flash initialized successfully
I (782) esp_qcloud_log_flash: Log save partition subtype: label: log_info, addr:0x3d0000, offset: 0, size: 65536
I (788) esp_qcloud_log: log initialized successfully
E (796) qcloud_light: The device has been restarted abnormally
E (801) esp_qcloud_device: Please check if the authentication information of the device is configured
E (811) esp_qcloud_device: Obtain authentication configuration information from login qcloud iothut: 
E (820) esp_qcloud_device: https://console.cloud.tencent.com/iotexplorer
E (828) esp_qcloud_device: product_id: PRODUCT_ID
E (833) esp_qcloud_device: device_name: DEVICE_NAME
E (839) esp_qcloud_device: device_secret: DEVICE_SECRET

和三元组“PRODUCT_ID” 这些有关系？  有测试用的没有。

**Comment by zhanzhaocheng** [comment]
有备用的参见看：https://github.com/espressif/esp-csi/blob/master/examples/connect_qcloud/devices_list.csv

> 注：运行示例前，请详细阅读[README](https://github.com/espressif/esp-csi/tree/master/examples/connect_qcloud) ，其中对运行过程有详细的说明

**Comment by zhanzhaocheng** [comment]
Hello, @cuityanxi

Closing this issue, feel free to reopen with more updates. Thanks.
