### ISSUE TITLE
Acquisition for the local time in the output data  (AEGHB-482)

### ISSUE THREAD

**Issue by 4444monkey** [espressif/esp-csi#152]
Hi there,

I'm trying to get the local timestamp. The current epochtime format was not in real-time (see the pics).
 Could anyone give me a tutorial on how I can achieve that?
![timestamp issue2](https://github.com/espressif/esp-csi/assets/136068099/8826490c-66b9-43eb-bae1-278ad6518bf8)
![timestamp issue](https://github.com/espressif/esp-csi/assets/136068099/80ff0b71-f5ed-4f00-93c4-4cf3757a9b87)

**Comment by MacChu0315-Espressif** [comment]
You can use the SNTP component in the ESP-IDF to convert the onboard time to real-world time. More specifically, you can refer to the [example](https://github.com/espressif/esp-idf/tree/master/examples/protocols/sntp) in the IDF repository.
