### ISSUE TITLE
ESP_FAIL in esp_wifi_set_csi function (AEGHB-501)

### ISSUE THREAD

**Issue by Snowleopold** [espressif/esp-csi#155]
I flashed the csi_recv code to my ESP32 board and this error appears:
![csierror](https://github.com/espressif/esp-csi/assets/113206098/53876c91-0dc0-4932-8c98-1eae0e6e3962)
Can anyone help with this issue?

**Comment by Snowleopold** [comment]
nvm issue fixed.

**Comment by Ho456** [comment]
You may check if channel state information is enabled in menuconfig. Enable it if it is not
