### ISSUE TITLE
Question about the feasibility of CSI data migration (receiver to Cloud platform) (AEGHB-514)

### ISSUE THREAD

**Issue by 4444monkey** [espressif/esp-csi#159]
Hi there,
I'd like to address a question if it is possible to transfer the collected CSI data from the receiver part to the Cloud platform.
It aims to apply the CSI data packet for further algorithm analysis like machine learning.
I would expect to use the sub-project of "csi_recv" equipped with the wifi function listening to another ESP device (as a transmitter) and then migrate the collected CSI data to the Cloud platform from the open-source.
If it is feasible how I can achieve that and avoid the interruption from the CSI data collection (the receiver part)?

Just found a decent demonstration like this:
![esp now and router](https://github.com/espressif/esp-csi/assets/136068099/593df16d-f4b5-46fe-9ffe-cc1c40cfde8b)

**Comment by MacChu0315-Espressif** [comment]
This approach is feasible. Have you encountered any specific issues during the implementation process? For example, did any interruptions occur while receiving CSI data?

**Comment by 4444monkey** [comment]
Since my project terminated, abort this trial currently.

**Comment by 4444monkey** [comment]
Since my project terminated, aborted this trial currently.
