### ISSUE TITLE
ESP32-C6-DevKit with an external antenna connecter (AEGHB-718)

### ISSUE THREAD

**Issue by TryTwoTop** [espressif/esp-csi#184]
The issue below says that it will support ESP32-C6, but the official ESP32-C6-based dev boards that currently exist are with built-in antennas.

Are there any plans to release a dev board with an external antenna?

If not, will I have to build my own dev board with a module with an external antenna connector?

**Comment by MacChu0315-Espressif** [comment]
Which issue are you referring to?
As far as I know, there isn't one. And, what functionality are you looking to implement?

**Comment by TryTwoTop** [comment]
@MacChu0315-Espressif 

Sorry about that. I forgot to include the link
[GitHub Issue: https://github.com/espressif/esp-csi/issues/179]

It says that using an external antenna works better than using a PCB antenna, so I asked if there are any plans to release a dev board with an external antenna.
*reference link
https://github.com/espressif/esp-csi?tab=readme-ov-file#5-note

**Comment by MacChu0315-Espressif** [comment]
I apologize, but we currently do not have plans for this.
If you wish to implement such a feature, there are several ways to achieve it:
    1. Design your own based on the 1u module.
    2. Use a development board with a PCB antenna, remove the existing module and replace it with a 1u module.
