### ISSUE TITLE
Variable name confusion in csi_data_read_parse.py file (AEGHB-723)

### ISSUE THREAD

**Issue by TryTwoTop** [espressif/esp-csi#187]
File path: esp-csi / examples / get-started / tools / csi_data_read_parse.py

Is it correct to change from phase to amplitude in the variable name self.csi_phase_array?

*Link
https://github.com/espressif/esp-csi/blob/master/examples/get-started/tools/csi_data_read_parse.py#L85

**Comment by suhipek** [comment]
I think you're correct. Indeed the result of `np.abs(csi_data_array)` should be its amplitudes. We will fix this typo in upcoming updates. Thank you for reporting it!
