### ISSUE TITLE
刷入console_test经常重启 (AEGHB-214)

### ISSUE THREAD

**Issue by m25u** [espressif/esp-csi#19]
你好，我刷入console_test之后控制经常滚动下面这些日志，命令好像也运行不了，
机器型号是eps32-cam
日志如下：
csi> ets Jun  8 2016 00:22:57

rst:0x8 (TG1WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:7024
load:0x40078000,len:14292
ho 0 tail 12 room 4
load:0x40080400,len:3700
0x40080400: _init at ??:?

entry 0x4008067c
I (57) boot: ESP-IDF v4.3-dirty 2nd stage bootloader
I (57) boot: compile time 23:14:59
I (58) boot: chip revision: 1
I (61) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (68) boot.esp32: SPI Speed      : 40MHz
I (73) boot.esp32: SPI Mode       : DIO
I (78) boot.esp32: SPI Flash Size : 4MB
W (82) boot.esp32: PRO CPU has been reset by WDT.
W (87) boot.esp32: WDT reset info: PRO CPU PC=0x400966c6
0x400966c6: xthal_save_extra_nw at /Users/igrokhotkov/e/esp32/hal/hal/state_asm.S:72

W (93) boot.esp32: WDT reset info: APP CPU PC=0x400897cc
0x400897cc: _xt_context_save at C:/Users/muchuanhao/esp/esp-idf/components/freertos/port/xtensa/xtensa_context.S:130

I (99) boot: Enabling RNG early entropy source...
I (105) boot: Partition Table:
I (109) boot: ## Label            Usage          Type ST Offset   Length
I (116) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (123) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (131) boot:  2 factory          factory app      00 00 00010000 00100000
I (139) boot: End of partition table
I (143) boot_comm: chip revision: 1, min. application chip revision: 0
I (150) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=1b1fch (111100) map
I (201) esp_image: segment 1: paddr=0002b224 vaddr=3ffb0000 size=043dch ( 17372) load
I (208) esp_image: segment 2: paddr=0002f608 vaddr=40080000 size=00a10h (  2576) load
I (209) esp_image: segment 3: paddr=00030020 vaddr=400d0020 size=89600h (562688) map
I (427) esp_image: segment 4: paddr=000b9628 vaddr=40080a10 size=15d20h ( 89376) load
I (465) esp_image: segment 5: paddr=000cf350 vaddr=50000000 size=00010h (    16) load
I (478) boot: Loaded app from partition at offset 0x10000
I (478) boot: Disabling RNG early entropy source...
I (490) cpu_start: Pro cpu up.
I (490) cpu_start: Starting app cpu, entry point is 0x40081418
0x40081418: call_start_cpu1 at C:/Users/muchuanhao/esp/esp-idf/components/esp_system/port/cpu_start.c:141

I (0) cpu_start: App cpu up.
I (504) cpu_start: Pro cpu start user code
I (504) cpu_start: cpu freq: 160000000
I (504) cpu_start: Application information:
I (508) cpu_start: Project name:     console_test
I (514) cpu_start: App version:      1
I (518) cpu_start: Compile time:     Sep  2 2021 23:15:13
I (524) cpu_start: ELF file SHA256:  b818b513474a37ee...
I (530) cpu_start: ESP-IDF:          v4.3-dirty
I (536) heap_init: Initializing. RAM available for dynamic allocation:
I (543) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (549) heap_init: At 3FFB8A40 len 000275C0 (157 KiB): DRAM
I (555) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (561) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (568) heap_init: At 40096730 len 000098D0 (38 KiB): IRAM
I (575) spi_flash: detected chip: generic
I (579) spi_flash: flash io: dio
I (584) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (594) gpio: GPIO[18]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0
I (654) wifi:wifi driver task: 3ffc1384, prio:23, stack:6656, core=0
I (654) system_api: Base MAC address is not set
I (654) system_api: read default base MAC address from EFUSE
I (674) wifi:wifi firmware version: c7d0450
I (674) wifi:wifi certification version: v7.0
I (674) wifi:config NVS flash: enabled
I (674) wifi:config nano formating: disabled
I (684) wifi:Init data frame dynamic rx buffer num: 32
I (684) wifi:Init management frame dynamic rx buffer num: 32
I (694) wifi:Init management short buffer num: 32
I (694) wifi:Init dynamic tx buffer num: 32
I (694) wifi:Init static rx buffer size: 2212
I (704) wifi:Init static rx buffer num: 10
I (704) wifi:Init dynamic rx buffer num: 32
I (714) wifi_init: rx ba win: 6
I (714) wifi_init: tcpip mbox: 32
I (714) wifi_init: udp mbox: 6
I (724) wifi_init: tcp mbox: 6
I (724) wifi_init: tcp tx win: 5744
I (734) wifi_init: tcp rx win: 5744
I (734) wifi_init: tcp mss: 1440
I (734) wifi_init: WiFi IRAM OP enabled
I (744) wifi_init: WiFi RX IRAM OP enabled
I (744) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07
I (844) wifi:mode : null
I (844) wifi:ic_enable_sniffer

Type 'help' to get the list of commands.
Use UP/DOWN arrows to navigate through command history.
Press TAB when typing command name to auto-complete.
Your terminal application does not support escape sequences.

Line editing and history features are disabled.

On Windows, try using Putty instead.

 =======================================================================
 |                    Steps to test CSI                                |
 |                                                                     |
 |  1. Print 'help' to gain overview of commands                       |
 |     csi> help                                                       |
 |  2. Start SoftAP or Sta on another ESP32/ESP32S2/ESP32C3            |
 |     csi> sta <ssid> <pwd>                                           |
 |     csi> ap <ssid> <pwd>                                            |
 |  3. Run ping to test                                                |
 |     csi> ping <ip> -c <count> -i <interval>                         |
 |  4. Configure CSI parameters                                        |
 |     csi> csi -m <mac(xx:xx:xx:xx:xx:xx)> -l <len>                   |
 |  5. Configure CSI parameters                                        |
 |     csi> detect -a <absolute_threshold> -r <relative_threshold>     |
 |                                                                     |
 ======================================================================

运行`ap csi_softap`
显示
![image](https://user-images.githubusercontent.com/57902632/131871651-5f1159a4-a42e-4b43-a6b3-f7c8d0abb757.png)

**Comment by zhanzhaocheng** [comment]
Hello, @m25u 

Closing this issue, feel free to reopen with more updates. Thanks.
