### ISSUE TITLE
Can I configure 'one' ESP32 module as a transceiver to get CSI data? (AEGHB-745)

### ISSUE THREAD

**Issue by TryTwoTop** [espressif/esp-csi#190]
Can an ESP32 transmit data wirelessly as a single module and receive data back to get CSI data?

**Comment by MacChu0315-Espressif** [comment]
sorry, can't do so

**Comment by liuchengzhi314159** [comment]
> 抱歉，不能这样做

意思是 我没有办法在向此开发板传输数据的同时，从这块开发板上获取传输数据当时的csi？既我没有办法实现双向csi测量
