### ISSUE TITLE
Request to update documentation for the ESP32-C6 HE20 subcarrier (AEGHB-756)

### ISSUE THREAD

**Issue by TryTwoTop** [espressif/esp-csi#194]
Hello

I modified the csi_send and csi_recv examples myself to fit the ESP32-C6 and successfully collected 256 subcarriers of HE20.
I would like to know the index of null carrier and pilot carrier in the subcarrier.
Will you update the information about HE20 subcarriers of ESP32-C6 in ESP-IDF Programming Guide in the future?

**Comment by MacChu0315-Espressif** [comment]
Hi, we will do but that won't come so fast i'm afraid.
