### ISSUE TITLE
Is there any difference between the CSI data collected on ESP32 and intel-5300?

### ISSUE THREAD

**Issue by strongerux** [espressif/esp-csi#22]

**Comment by 2422092593zhangshuo** [comment]
If I want to control the received CSI length,what I should limit the Wi-Fi communication method of the packet sending device. Could you give me some advice?

**Comment by strongerux** [comment]
Screen from all datas,for me.

**Comment by 2422092593zhangshuo** [comment]
How to screen？Are you using algorithms or visualizations？Could you give me some advice?
