### ISSUE TITLE
The ESP32 cannot ping the router

### ISSUE THREAD

**Issue by 2422092593zhangshuo** [espressif/esp-csi#23]
I used an ESP32 and a router to collect channel status information, set the router as AP and ESP32 as STA, and finally used ESP32 to ping the router, which failed. Come to consult。
![捕获1](https://user-images.githubusercontent.com/63175163/138662124-b550d45e-cfe7-449c-a6d1-9d6f68c8f5c3.PNG)
![捕获2](https://user-images.githubusercontent.com/63175163/138662173-c2be68d0-b8e8-4a7d-94df-d62bf446b223.PNG)
![捕获3](https://user-images.githubusercontent.com/63175163/138662214-e9840c82-d7c2-42d0-8936-cfd3c59bc2be.PNG)
![捕获4](https://user-images.githubusercontent.com/63175163/138662264-5503b927-25cf-4dfa-8ee4-771bde82a980.PNG)

**Comment by 2422092593zhangshuo** [comment]
Excuse me, I would like to ask you about the difference between ESP32 and Intel5300 in collecting CSI. Could you give me some advice?

**Comment by zhanzhaocheng** [comment]
@2422092593zhangshuo See https://github.com/espressif/esp-csi/issues/22

**Comment by 2422092593zhangshuo** [comment]
Thank you very much. Is the length of CSI  received by ESP32 related to the number of antennas on the router?

**Comment by 2422092593zhangshuo** [comment]
The CSI data I collected was carried out under the condition of 20MHz HT,no seconary_channel and stbc. The length of CSI data is 256，how should LLTF and HT-LTF subcarrier indexes be distinguished. Could you give me some help? Thank you

**Comment by zhanzhaocheng** [comment]
@2422092593zhangshuo 
```c
#define CSI_SUBCARRIER_LLTF_LEN                  52 /**< 6 ~ 31 33 ~ 58 ---> 52 */
#define CSI_SUBCARRIER_HTLTF_LEN               56 /**< 66 ~ 122       ---> 56 */
#define CSI_SUBCARRIER_STBC_HTLTF_LEN   56 /**< 123 ~ 191      ---> 56 */
```

**Comment by 2422092593zhangshuo** [comment]
Thanks you for the reply. Calculated in this way, LLTF_LEN is  52,HTLTF_LEN is 56 STBC_HTLTF_LEN is 68.
what's your opinion? Could you give me some advice? Thank you.

**Comment by 2422092593zhangshuo** [comment]
Thanks you for the reply. Calculated in this way, LLTF_LEN is  52,HTLTF_LEN is 57 STBC_HTLTF_LEN is 69.
what's your opinion? Could you give me some advice? Thank you.

**Comment by 2422092593zhangshuo** [comment]
Thanks you for the reply. Calculated in this way, LLTF_LEN is 52,HTLTF_LEN is 57,STBC_HTLTF_LEN is 69.
what's your opinion? Could you give me some advice? Thank you.

**Comment by zhanzhaocheng** [comment]
Because some of the sub-carriers have very small amplitude variances, they are filtered

**Comment by 2422092593zhangshuo** [comment]
Thank you.The length of CSI data I collected was 256.
#define CSI_SUBCARRIER_LLTF_LEN                  52 /**< 6 ~ 31 33 ~ 58 ---> 52 */
#define CSI_SUBCARRIER_HTLTF_LEN               56 /**< 66 ~ 122       ---> 56 */
Can I take it this way？

**Comment by zhanzhaocheng** [comment]
This needs to be judged based on the received Wi-Fi communication protocol, see: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/wifi.html#wi-fi-channel-state-information

![image](https://user-images.githubusercontent.com/19528396/143014322-f22ae5a8-18e5-4317-b718-a8d04cf37f7f.png)

**Comment by zhanzhaocheng** [comment]
Hello, @2422092593zhangshuo 

Closing this issue, feel free to reopen with more updates. Thanks.
