### ISSUE TITLE
Bugs in examples/console_test/tools/analisys_csi_data?

### ISSUE THREAD

**Issue by jimbojumbo** [espressif/esp-csi#24]
In the examples/console_test/tools/analisys_csi_data.py line 65, the assumption is that the first byte of each channel response is the real number and the second one is the imaginary number. However this contradicts the statement in the ESP32 Wi-Fi Channel State Information documentation where it says "Each channel frequency response of sub-carrier is recorded by two bytes of signed characters. The first one is imaginary part and the second one is real part."  Can you please verify the which one is the correct in order to reconstruct the CSI complex data from the byte data? Thanks.

<img width="686" alt="Screen Shot 2021-10-25 at 3 04 41 PM" src="https://user-images.githubusercontent.com/12279687/138776826-9a7db206-1f92-4a34-a84b-82e2a303079c.png">

**Comment by zhanzhaocheng** [comment]
This issue has been fixed，Closing this issue, feel free to reopen with more updates. Thanks.
