### ISSUE TITLE
Missing cmd_system.h file

### ISSUE THREAD

**Issue by dazzalicious** [espressif/esp-csi#25]
I am new to programming the ESP32-C3 chip and want to get the CSI data for distance ranging between two chips. I've tried to clone your repo for some ideas but I am getting this error trying to flash the console_test program to my chip. I can see a system_cmd.c file in your main folder but no cmd_system.h file.

![Screenshot from 2021-10-30 16-03-02](https://user-images.githubusercontent.com/82013892/139521119-3dc6f1f1-ff3f-4b25-b1a4-93bc0f0b677f.png)

**Comment by dazzalicious** [comment]
It seems that simply commenting out the #include cmd_system.h lines allows this to work.

**Comment by zhanzhaocheng** [comment]
This is caused by a change in the version of ESP-IDF.
He only affects the console:https://github.com/espressif/esp-idf/tree/master/examples/system/console

**Comment by zhanzhaocheng** [comment]
Hello, @dazzalicious

Closing this issue, feel free to reopen with more updates. Thanks.
