### ISSUE TITLE
useful subcarrier channel in tools/analisys_csi_data.py

### ISSUE THREAD

**Issue by erusyd** [espressif/esp-csi#26]
Can anyone explain what are the useful subcarrier channels in tools/analisys_csi_data.py:

![image](https://user-images.githubusercontent.com/1529102/139634425-fe6b472a-a502-4533-b152-eeb97015ad7f.png)

Where can I find any clue in the official documents?

It seems that the amplitude of some other subcarrier channels are also negligible. Below is the plot of one of my data sampling:
![image](https://user-images.githubusercontent.com/1529102/139635149-c506a22e-a986-4ee7-a299-59176342a777.png)

**Comment by zhanzhaocheng** [comment]
You can calculate the variance of each sub-carrier and filter the sub-carriers with very small variance

**Comment by erusyd** [comment]
Thanks.
