### ISSUE TITLE
On timestamp interval between successive CSI feedback

### ISSUE THREAD

**Issue by erusyd** [espressif/esp-csi#27]
I use
_ping 192.168.4.1 -i 0.2_
to set the time interval to 0.2 seconds, but I get the following time intervals by differentiating successive CSI feedback local_timestamp:

![image](https://user-images.githubusercontent.com/1529102/141057532-16c76071-2593-4db5-8a3d-df9338b58e84.png)

As you can see, most intervals are approximately 0.2s. What I can understand are those ~0.4s and ~0.6s intervals which may be caused by extra ping time waiting or packet loss, but I can't figure out why there are many ~0.01s intervals. Can I simply remove those samples?

**Comment by kallu1294** [comment]
> I use _ping 192.168.4.1 -i 0.2_ to set the time interval to 0.2 seconds, but I get the following time intervals by differentiating successive CSI feedback local_timestamp:
> 
> ![image](https://user-images.githubusercontent.com/1529102/141057532-16c76071-2593-4db5-8a3d-df9338b58e84.png)
> 
> As you can see, most intervals are approximately 0.2s. What I can understand are those ~0.4s and ~0.6s intervals which may be caused by extra ping time waiting or packet loss, but I can't figure out why there are many ~0.01s intervals. Can I simply remove those samples?

Hi 

For this we need two esp32 board right.? one for AP and another one of STA so we can get the CSI DATA 

thanks in advance

**Comment by erusyd** [comment]
@kallu1294 Although you can use another commercial AP, but it is recommended to use two esp32 boards to get stable and consistent CSI data.

**Comment by kallu1294** [comment]
> @kallu1294 Although you can use another commercial AP, but it is recommended to use two esp32 boards to get stable and consistent CSI data.

Thanks for the reply 
Is there any method to download this CSI _DATA..??

**Comment by kallu1294** [comment]
> I use _ping 192.168.4.1 -i 0.2_ to set the time interval to 0.2 seconds, but I get the following time intervals by differentiating successive CSI feedback local_timestamp:
> 
> ![image](https://user-images.githubusercontent.com/1529102/141057532-16c76071-2593-4db5-8a3d-df9338b58e84.png)
> 
> As you can see, most intervals are approximately 0.2s. What I can understand are those ~0.4s and ~0.6s intervals which may be caused by extra ping time waiting or packet loss, but I can't figure out why there are many ~0.01s intervals. Can I simply remove those samples?

Hello sir
 how can we see the received CSI_DATA like this.??

**Comment by erusyd** [comment]
Use ctrl+t, ctrl+l to log the data. You should read the readme of this repository first.
