### ISSUE TITLE
Generating CSI data into graphs 

### ISSUE THREAD

**Issue by kallu1294** [espressif/esp-csi#29]
Hi everyone 
Now i have a CSI data so i need to plot those data into graphs how can i do that anybody can suggest me how can i do that..??
And how can differentiate imaginary and real data ..??

**Comment by zhanzhaocheng** [comment]
Please refer [here](https://github.com/espressif/esp-csi/tree/master/examples/console_test/tools)

**Comment by kallu1294** [comment]
> Please refer [here](https://github.com/espressif/esp-csi/tree/master/examples/console_test/tools)

Thanks for the reply :-)

**Comment by kallu1294** [comment]
> Please refer [here](https://github.com/espressif/esp-csi/tree/master/examples/console_test/tools)

Already i have csi_data in csv file which i did from other source(repo) and now i need to plot waveform(analyze) for those data how can i do that any suggestions ...??
And i went through your suggestions but i didn't get anything there,means if i run the commands which are present that link it is shown error as bash:  ./analysis_csi_data.py : no such file or directory

**Comment by zhanzhaocheng** [comment]
Each channel frequency response of sub-carrier is recorded by two bytes of signed characters. The first one is imaginary part and the second one is real part.
refer to: https://github.com/espressif/esp-csi/issues/24

**Comment by zhanzhaocheng** [comment]
Hello, @kallu1294 

Closing this issue, feel free to reopen with more updates. Thanks.
