### ISSUE TITLE
Cannot save CSI data from device log

### ISSUE THREAD

**Issue by syahirseth** [espressif/esp-csi#30]
![82388d0e-1512-4107-96a7-af02c2a4ebbc](https://user-images.githubusercontent.com/97726352/149472350-38cf7795-067c-4b8f-bb90-9bf554872a9c.jpg)
Hi, i have a problem where i cannot save the CSi raw data using ctrl+t , ctrl+l after command "csi -o". can you give more details step on how to save the data. and from the photo actually i clicked ctrl+T but it says ctrl+J. hope you guys can help me

**Comment by zhanzhaocheng** [comment]
I usually use the [minicom](https://linux.die.net/man/1/minicom) tool for log saving, the commands I use are as follows:
```shell
minicom -c on -D /dev/cu.usbserial-1430 -b 921600 -C test.log
```

**Comment by zhanzhaocheng** [comment]
Hello, @syahirseth 

Closing this issue, feel free to reopen with more updates. Thanks.
