### ISSUE TITLE
Where's the defination of esp_wifi_rader_x api?

### ISSUE THREAD

**Issue by UncleBigLu** [espressif/esp-csi#31]
I found esp_wifi_radar_init declaration in esp_radar.h but can not found it's implementation. Is the implementation available to user? Or where could I find document about function in esp_radar.h?

**Comment by zhanzhaocheng** [comment]
The implementation in esp_wifi_radar_init is not open source for the time being, you can use CSI raw data for analysis
[Wi-Fi Channel State Information](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/wifi.html#wi-fi-channel-state-information)
