### ISSUE TITLE
wifi_radar_cb never called

### ISSUE THREAD

**Issue by userid7** [espressif/esp-csi#32]
I have built and flash the code to ESP32 and successfully run the esp-csi console-test example program. but when I ping the router or device in the network, there is no CSI information shown like what is said in the readMe file (ex : (526744) app_main: <1> time: 1030 ms, rssi: -26, corr: 0.959, std: 0.008, std_avg: 0.000, std_max: 0.000, threshold: 0.300/1.500, trigger: 0/0, free_heap: 134928/137440
). The only thing that showed up was just the ping success information. but when I run "csi -o" command to get csi raw data the raw data showed up on the screen. It seems that the wifi_radar_cb never called even when there is CSI data. Do you have any suggestions?

`I (17584) system_cmd: compile time     : Jan 15 2022 16:48:17
I (17584) system_cmd: free heap        : 208600 Bytes
I (17584) system_cmd: CPU cores        : 2
I (17594) system_cmd: silicon revision : 1
I (17594) system_cmd: feature          : /802.11bgn/BLE/BT/External-Flash:4 MB
I (34994) wifi_cmd: sta connecting to 'TEST'
I (35004) wifi:mode : sta (e8:db:84:37:51:4c)
I (35004) wifi:enable tsf
I (35374) wifi:new:<4,0>, old:<1,1>, ap:<255,255>, sta:<4,0>, prof:1
I (36104) wifi:state: init -> auth (b0)
I (36154) wifi:state: auth -> assoc (0)
I (36164) wifi:state: assoc -> run (10)
I (36194) wifi:connected with TEST, aid = 1, channel 4, BW20, bssid = 22:ad:b9:f8:d9:8d
I (36194) wifi:security: WPA2-PSK, phy: bgn, rssi: -14
I (36194) wifi:pm start, type: 1

I (36214) wifi:AP's beacon interval = 102400 us, DTIM period = 2
I (36214) wifi_cmd: Connected to TEST (bssid: 22:ad:b9:f8:d9:8d, channel: 4)
I (37044) esp_netif_handlers: sta ip: 192.168.43.27, mask: 255.255.255.0, gw: 192.168.43.1
csi> W (61324) wifi:<ba-add>idx:0 (ifx:0, 22:ad:b9:f8:d9:8d), tid:0, ssn:3, winSize:64
I (61474) ping_cmd:
--- 192.168.43.1 ping statistics ---
I (61474) ping_cmd: 10 packets transmitted, 10 received, 0% packet loss, time 69ms
csi> I (91094) ping_cmd: i 1
--- 192.168.43.1 ping statistics ---
I (91094) ping_cmd: 10 packets transmitted, 10 received, 0% packet loss, time 339ms`

**Comment by zhanzhaocheng** [comment]
That may require modifying csi data filter conditions, such as length or MAC address, see: https://github.com/espressif/esp-csi/tree/master/examples/console_test#how-to-use
````
csi> csi -l 256 -m 22:ad :b9:f8:d9:8d
````

**Comment by zhanzhaocheng** [comment]
Hello, @userid7 

Closing this issue, feel free to reopen with more updates. Thanks.
