### ISSUE TITLE
What is the "useful subcarrier index" In analysis_csi_data.py

### ISSUE THREAD

**Issue by 14YUMIKI** [espressif/esp-csi#34]
I really appreciate that you provide us very efficient tool for analyzing CSI, but I got a question just like the title of this issue. In analysis_csi_data.py, you picked 174 amplitudes of subcarries to plot. However, my understanding is that IEEE 802.11.a/n uses 52 subcarriers to send data, so the number of amplitude should be up to 52. In my research, these 174 amplitudes worked very well, but I want to make sure what these 174 amplitudes are.

**Comment by zhanzhaocheng** [comment]
OFMD generates 64 points when performing FFT transformation, so it will dump 64 data, of which 56 are valid and both sides are invalid
LLTF can be calculated as a group of data, HT-LTF can also be calculated as a group, STBC-HT-LTF is also a group, equivalent to 3 groups of data
-32~-1, 1~+32 ==> -28 ~ +28
0~63 ==> 4~60

**Comment by zhanzhaocheng** [comment]
Hello, @14YUMIKI 

Closing this issue, feel free to reopen with more updates. Thanks.
