### ISSUE TITLE
Esp32 detect the change of human breathing？ (AEGHB-63)

### ISSUE THREAD

**Issue by zhy102** [espressif/esp-csi#35]
Thank you for the information, I would like to ask: **Could the csi extracted from esp32 detect the change of human breathing? Could adding an external antenna improve the sensitivity a lot, and could the sampling rate of csi be set?**

**Comment by zhanzhaocheng** [comment]
- Breath testing is theoretically possible
- External antenna can improve sensitivity
- CSI sampling rate can be set

**Comment by zhy102** [comment]
您发给我的邮件我已收到。

**Comment by zhy102** [comment]
OK, thanks.&nbsp;Best regards!



---Original---
From: ***@***.***&gt;
Date: Mon, Feb 28, 2022 16:14 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [espressif/esp-csi] Esp32 detect the change of human breathing？ (Issue #35)




  
Breath testing is theoretically possible 

External antenna can improve sensitivity 

CSI sampling rate can be set 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kavya1229** [comment]
How can we detect breathing from wifi csi?

**Comment by zhanzhaocheng** [comment]
You can view relevant papers: https://ieeexplore.ieee.org/search/searchresult.jsp?newsearch=true&queryText=wifi%20csi%20%20breath

**Comment by zenbooster** [comment]
Is it possible multi-person Respiration Sensing, as described here, but with multiple esp32 boards:
https://www.researchgate.net/publication/343361467_MultiSense_Enabling_Multi-person_Respiration_Sensing_with_Commodity_WiFi
?

**Comment by zhanzhaocheng** [comment]
Hello, @zhy102 

Closing this issue, feel free to reopen with more updates. Thanks.
