### ISSUE TITLE
Power-down loss after burn-in

### ISSUE THREAD

**Issue by zhy102** [espressif/esp-csi#38]
After flashing, I perform `ap <myssid> <mypassword>` test, but when it is re-powered, the WIFI hotspot is gone? This is also the case when I do the `sta` test, besides, he can't connect to my smart phone hotspot, can you help me?

**Comment by zhanzhaocheng** [comment]
Can you provide a log of your not being able to connect?

**Comment by zhanzhaocheng** [comment]
Hello, @zhy102 

Closing this issue, feel free to reopen with more updates. Thanks.
