### ISSUE TITLE
further advance the baud rate of the serial port

### ISSUE THREAD

**Issue by zhy102** [espressif/esp-csi#42]
My OS is windows10.
Test on ''[esp-csi](https://github.com/espressif/esp-csi)/[examples](https://github.com/espressif/esp-csi/tree/master/examples)/get-started/''.
The errors are coming as follows when i called "python csi_data_read_parse.py -p COM5":
```
open success
data is not incomplete
element number is not equal
```
**So i want to konw how to further advance the baud rate of the serial port? And the Windows systems support up to 128000.  Can Ubuntu systems support higher baud rates?**

**Comment by zhy102** [comment]
> 
This live image is stuck after some waveforms appear.

**Comment by zhanzhaocheng** [comment]
The baud rate of serial port can be set to 2Mbps at most. For the setting method, see: [How to change esp32 console baudrate](https://github.com/espressif/esp-csi/tree/master/examples/console_test#how-to-change-esp32-console-baudrate)

**Comment by zhanzhaocheng** [comment]
> > 
> 
> This live image is stuck after some waveforms appear.

Do you scale the graph? Under what circumstances can it be reproduced and what is the probability of reproduction? Will it work after you restart the python script?

**Comment by zhanzhaocheng** [comment]
Hello, @zhy102 

Closing this issue, feel free to reopen with more updates. Thanks.
