### ISSUE TITLE
Is ESP32 CSI support MIMO? (AEGHB-111)

### ISSUE THREAD

**Issue by UncleBigLu** [espressif/esp-csi#47]
As far as I know, CSI is a martrix which dimension is rx_antenna_num*tx_antenna_num*subcarrier_num。For example when collecting CSI using intel 5300 card which has three antenna and a router which has two antenna, the CSI data per frame would be a 3*2*30 martrix.
Although ESP32 only support one antenna, is it possible for esp32 to get 1*n*subcarrier_num CSI when AP has n antenna work at the same time?

**Comment by N16104872** [comment]
I have the same question too. Can anybody answer for us plz.

**Comment by kszlgithub** [comment]
ESP32 don't support MIMO sending for ESP32 chips have one antenna per chip. But ESP32 do support receiving MIMO signals.

**Comment by zhanzhaocheng** [comment]
Hello, @UncleBigLu @N16104872

Closing this issue, feel free to reopen with more updates. Thanks.
