### ISSUE TITLE
esp32c3无法使用connect_qcloud例子

### ISSUE THREAD

**Issue by homent-hutu** [espressif/esp-csi#50]
ninja: error: '/home/code/esp/esp-csi/lib/esp32c3/libesp-csi.a', needed by 'connect_qcloud.elf', missing and no known rule to make it

**Comment by zhanzhaocheng** [comment]
At present, qcloud is not adapted in the optimization algorithm. Please test based on [console_test](https://github.com/espressif/esp-csi/tree/master/examples/console_test) first

**Comment by zhanzhaocheng** [comment]
Due to the higher complexity of the current algorithm, the performance of esp32-c3 cannot be met

**Comment by zhanzhaocheng** [comment]
The latest version has replaced qcloud with RainMaker, and it can work normally on ESP32-C3/ESP32-S3/ESP32-S2/ESP32，Closing this issue, feel free to reopen with more updates. Thanks.
