### ISSUE TITLE
CSI Data

### ISSUE THREAD

**Issue by pampariumeshchandra** [espressif/esp-csi#54]
Hi!!I am trying to collect CSI data from ESP32 Wrover-B.I want to know whether there is a limit for CSI data and where does the CSI data store in ESP32 if we are not monitoring in the Laptop.If there is a limit,will it reset and can we access the reset data.

**Comment by zhanzhaocheng** [comment]
You can connect an SD card to store CSI data in the SD card

**Comment by zhanzhaocheng** [comment]
Hello, @pampariumeshchandra 

Closing this issue, feel free to reopen with more updates. Thanks.
