### ISSUE TITLE
Use libesp-csi.a in the other projects as well in ESP-IDF 4.4.1

### ISSUE THREAD

**Issue by filzek** [espressif/esp-csi#59]
Hi,

We tried to move out the libesp-csi.a to be used in the esp-idf v.4.4.1 and we cant make it work there.

Can you please advise what shall be done? we have our project already built in and we want to use the WiFi radar inside our project but once we try to use it, it simple doenst wortk as references doesnt work.

Is that possible to just add the correct cmake files as an reply to be used elsewhere?

**Comment by zhanzhaocheng** [comment]
Yes, you only need to include `libesp-csi.a` and `esp_radar.h`, add the following code to the makefile, see for 

details:
- https://cmake.org/cmake/help/v3.16/command/target_link_libraries.html#command:target_link_libraries
- https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/build-system.html?highlight=target_link_libraries#build-system

````makefile
idf_component_register(INCLUDE_DIRS "include")
target_link_libraries(${COMPONENT_LIB} INTERFACE "${CMAKE_CURRENT_LIST_DIR}/lib/libesp-csi.a")
````


But please keep paying attention to this project. I have optimized the detection algorithm for moving, stationary, people and unmanned people, and its accuracy has been greatly improved. I will gradually update it to github in the next few weeks.

**Comment by zhanzhaocheng** [comment]
Hello, @filzek 

Closing this issue, feel free to reopen with more updates. Thanks.
