### ISSUE TITLE
CSI resolution and phase unwrapping

### ISSUE THREAD

**Issue by NaivelyWritten** [espressif/esp-csi#61]
Hi,

In my experiment all CSI values seems to fall in the range of -16-16, is this intended? A byte should have a range of -128-127?

Also, the CSI order seems to be different when associated with an AP, when unassociated the CSI is from 0-31, -31- -1, but after association it becomes -31-31.

Thanks a lot!

**Comment by zhanzhaocheng** [comment]
The value of csi is between -128 and 127, and the received signal amplitude and phase are related

**Comment by NaivelyWritten** [comment]
Thanks for the reply! However the problem I have is that it is indeed -128-127 for HT-LTF, but for L-LTF it's only -16-16.
And also the order is different when associated/unassociated.

我的测试里面 L-LTF 部分只有 -16-16 的范围，另外如果和AP处于连接状态的时候 CSI 的顺序是反的。

**Comment by zhanzhaocheng** [comment]
You can observe the value of L-LTF by changing the distance between the device and the AP.
You can try the [console_test](https://github.com/espressif/esp-csi/tree/master/examples/console_test) example to observe the subcarrier changes

**Comment by zhanzhaocheng** [comment]
Hello, @NaivelyWritten 

Closing this issue, feel free to reopen with more updates. Thanks.
