### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by JLnukeNV** [espressif/esp-csi#62]
I'm getting some problem using the esp_csi_tool.py, the issue is when we use a computer with poor I/O or cpu performance, for example our laptop without charger, there will be some problem reading the strings from serial port.
![3b119bb95d330459dc7f97e16953ba3](https://user-images.githubusercontent.com/45910525/177671229-20368a3a-2cd1-4144-888c-a913e41e133b.png)
![135b7d1ab30ffb8297657cbdd5ab36d](https://user-images.githubusercontent.com/45910525/177671174-772deee3-8a21-4690-b47b-eb8c560d2b35.png)
In the above pictures, obviously the data invalid, causing the whole frame lost.
In that case we can cope with the issue by using a more powerful PC, but it isn't just about the performance. esp_csi_tool.py writes each CSI_DATA into csi_data.csv, as the file getting larger, the handling speed will slow down and cause the issue above. A new version of esp_csi_tool.py is needed.

**Comment by zhanzhaocheng** [comment]
This is because the read and write speed of the serial port is too slow, resulting in data loss. At present, this problem has been fixed, please update

**Comment by zhanzhaocheng** [comment]
Hello, @JLnukeNV 

Closing this issue, feel free to reopen with more updates. Thanks.
