### ISSUE TITLE
Using two esp32 (AEGHB-218)

### ISSUE THREAD

**Issue by Tisha36** [espressif/esp-csi#65]
I want to use two esp32 for CSI collection. I I will use one esp as transmitter and another one as receiver. So when i go through the interface window ,in the router connection window ,what should i give in the field of  router ssid and password part.
Thanks.

**Comment by zhanzhaocheng** [comment]
No need to enter router information if using two ESP32s
Make sure your project is up to date

**Comment by Gowtham-Gorajana** [comment]
@zhanzhaocheng Can you please provide more information with detailed explanation on how we can use two esp32s with the given source files so that we can detect any human passing between the transmitter and the receiver.
Any paper or a video link would be very much helpful.
Thanks

**Comment by zhanzhaocheng** [comment]
@Gowtham-Gorajana Sorry no one got back to you earlier.

You can run `examples/get-started/csi_recv` on one device and `examples/get-started/csi_send` on the other, and it will meet your needs

**Comment by zhanzhaocheng** [comment]
Hello, @Gowtham-Gorajana 

Closing this issue, feel free to reopen with more updates. Thanks.
