### ISSUE TITLE
CSI Data

### ISSUE THREAD

**Issue by tiyuuu** [espressif/esp-csi#66]
From CSI data we get bandwidth, noise, aggregation, csi value ,mac etc. But how these value can help for plant monitoring or human activity recognition or in other projects.
I am new to this field. So I can't understand.
Thanks in advance.

**Comment by zhanzhaocheng** [comment]
Through further processing of this information, it can help us improve the accuracy of detection
For example, through the Mac address, we can obtain the source device of the CSI data, and process the CSI information sent by different devices separately; through the noise, we can obtain the interference of the network environment, and judge whether the network environment meets the detection requirements when the device is arranged. noise for corresponding data processing

**Comment by tiyuuu** [comment]
> Through further processing of this information, it can help us improve the accuracy of detection For example, through the Mac address, we can obtain the source device of the CSI data, and process the CSI information sent by different devices separately; through the noise, we can obtain the interference of the network environment, and judge whether the network environment meets the detection requirements when the device is arranged. noise for corresponding data processing

And from amplitudes and phase for each frame of CSI data, what can we understand?

**Comment by zhanzhaocheng** [comment]
Channel state information can reflect the physical properties of the channel, including multipath delay, Doppler frequency shift, beamforming vector and other multipath effects in the time domain as amplitude attenuation, phase offset and time delay

**Comment by tiyuuu** [comment]
Thanks. Can  you suggest how to preprocess the CSI data to remove environmental noise?
I found this type of CSV file of CSI data, where I get noise floor
![data 1](https://user-images.githubusercontent.com/108349442/181877998-6f236e21-63ed-43cf-9205-f5f9d9fa43d1.PNG)

**Comment by zhanzhaocheng** [comment]
You can process CSI data through Kalman, IIR and other filtering algorithms. At the same time, it is strongly recommended that you use the development board of esp32-s3 external antenna for development. Esp32-s3 Wi Fi has better RF performance and better directivity of external antenna

**Comment by zhanzhaocheng** [comment]
Hello, @tiyuuu 

Closing this issue, feel free to reopen with more updates. Thanks.
