### ISSUE TITLE
ESP32C3

### ISSUE THREAD

**Issue by roberbike** [espressif/esp-csi#67]
I am trying to compile the csi_recv_router on Esp32c3 chip, but I have the following issue:
![image](https://user-images.githubusercontent.com/20878412/181995838-139d7fb5-2229-4edd-8867-71615f0f3606.png)

Is not valid this chip for this proyect?
Thanks.

**Comment by zhanzhaocheng** [comment]
esp32-c3 is supported, but it is recommended that you use esp32-s3

Your problem is that you need to clear the original compilation environment first because of switching between different chips. You run `idf Py fullclean ` or ` idf Py clean ` or `rm -rf build`

**Comment by roberbike** [comment]
Thank. fullclean was the solution.
