### ISSUE TITLE
examples/console_test was compilation error on esp32-c3

### ISSUE THREAD

**Issue by michan06** [espressif/esp-csi#70]
Thank you for sharing great project!!

I want to run console_test on esp32-c3, but set-target  esp32c3 and build, I encountered following error.
> ninja: error: '****/esp-csi/lib/esp32c3/libesp-csi.a', needed by 'console_test.elf', missing and no known rule to make it

After this commit  
https://github.com/espressif/esp-csi/commit/d183220e97c23b6ded528bf8ae2cc0c0d56ab9db ,
esp32-c3 and esp32-s2's "libesp-csi.a" was deleted.

![image](https://user-images.githubusercontent.com/11985292/185899925-bd0710c5-16e8-424a-adbe-82331c4c069c.png)

Please tell me that console_test supports esp32-c3 or not.

Thank you.

**Comment by zhanzhaocheng** [comment]
The processing power of esp32-C3 is very weak, so CSI development based on ESP32-C3 is not recommended, and console_test is not configured for ESP32-C3

**Comment by michan06** [comment]
I understand that use of esp-csi on 
esp-c3 in  is not recommended.  Thank you.

**Comment by zhanzhaocheng** [comment]
Hello, @michan06 

The latest version has fixed this problem. Closing this issue, feel free to reopen with more updates. Thanks.
