### ISSUE TITLE
Could you recommend some papers related to positioning with esp32s3?

### ISSUE THREAD

**Issue by xiaokangkang6** [espressif/esp-csi#72]
I want to learn to use esp32s3 for positioning, but I don't know the relevant principles very well. Can you recommend some literatures?

**Comment by zhanzhaocheng** [comment]
see: https://github.com/espressif/esp-idf/tree/master/examples/wifi/ftm

**Comment by xiaokangkang6** [comment]
> see: https://github.com/espressif/esp-idf/tree/master/examples/wifi/ftm

Thank you very much!!! But if I only know the distance without direction, how can I know the specific location?

**Comment by zhanzhaocheng** [comment]
Hello, @xiaokangkang6 

Closing this issue, feel free to reopen with more updates. Thanks.
