### ISSUE TITLE
wi-fi CSI和BLE同时工作的问题

### ISSUE THREAD

**Issue by muqiu-z** [espressif/esp-csi#73]
1.当ESP32与路由器连接，不断ping采集CSI的同时，能否通过蓝牙实时将采集的信息发送出去呢？
2.目前使用的芯片是ESP32s3，从网上了解到的信息是ESP32是蓝牙和wifi单天线分时双工，不知是否准确？
3.有没有其他ESP32芯片能支持该方案或者是否有其他方案能实现CSI采集的同时，无线传输出去呢？

**Comment by zhanzhaocheng** [comment]
1. No, the amount of CSI data is too large, and the BLE bandwidth is not enough. Can send CSI data over Wi-Fi
2. Yes
3. ESP32-C2, ESP32-S3, ESP32-S2, ESP32 all support CSI

**Comment by dfx1822375** [comment]
@muqiu-z ：您好，我最近在尝试采集CSI数据可以留个邮箱交流下么？万分感谢

**Comment by muqiu-z** [comment]
> 

好

**Comment by muqiu-z** [comment]
> @muqiu-z ：您好，我最近在尝试采集CSI数据可以留个邮箱交流下么？万分感谢

好

**Comment by Sunlu2333** [comment]
您好，请问您有尝试过一发多收获取CSI， 然后通过一个ESP32侦听这些链路的CSI再通过其他方式传输出去吗？

**Comment by zhanzhaocheng** [comment]
Yes, the raw data of CSI can be transmitted to PC through UART or stored in SD card
