### ISSUE TITLE
CSI Acquisition Issues

### ISSUE THREAD

**Issue by dfx1822375** [espressif/esp-csi#74]
Hello, I want to work on CSi signal acquisition through ESP32, but I have not used ESP32, and I want to get a little help.
    First of all, which ESP32 development board should I choose, what software should I install after I get the board, and do I need to install other software besides idf? And finally how do I start signal acquisition?
    Thank you for your answer.

**Comment by zhanzhaocheng** [comment]
It is recommended that you use ESP32-S3, it has better performance
https://github.com/espressif/esp-csi/tree/master/examples/console_test#esp-csi-console_test

**Comment by zhanzhaocheng** [comment]
Hello, @dfx1822375 

Closing this issue, feel free to reopen with more updates. Thanks.
