### ISSUE TITLE
problems about ESP connected to commodity WiFi routers

### ISSUE THREAD

**Issue by jiechen0809** [espressif/esp-csi#75]
Hi, when I connected the ESP32s2 with commodity WiFi routers, there are always different types of CSI packets(such as 384 bytes or 612 bytes), which maybe because of STBC or non-STBC. But even though I filter the CSI packets according to the length of CSI, there are always different types of CSI packets frequently because of the long GI or short GI, which will result in the fluctuation of CSI data( no matter amplitude or phase).  This phenomenon will result in the wrong person detection results. And filtering the packets according to length of CSI will lead to the result of no satisfied CSI packets. 
So, is thers any method that can control the type of CSI packets? For example, there are only non-STBC and long GI CSI packets, which can produce stable CSI data.
Another question, is it possible that the product which can get 1*2 tx-rx WiFi link CSI data will  be available soon? 
Thanks. Any help would be highly appreciated.
![1664522709309](https://user-images.githubusercontent.com/89521673/193214784-0e20b912-da63-44a7-ac26-75ebe5c31ac4.png)

**Comment by jiechen0809** [comment]
> Hi, when I connected the ESP32s2 with commodity WiFi routers, there are always different types of CSI packets(such as 384 bytes or 612 bytes), which maybe because of STBC or non-STBC. But even though I filter the CSI packets according to the length of CSI, there are always different types of CSI packets frequently because of the long GI or short GI, which will result in the fluctuation of CSI data( no matter amplitude or phase). This phenomenon will result in the wrong person detection results. And filtering the packets according to length of CSI will lead to the result of no satisfied CSI packets. So, is thers any method that can control the type of CSI packets? For example, there are only non-STBC and long GI CSI packets, which can produce stable CSI data. Another question, is it possible that the product which can get 1*2 tx-rx WiFi link CSI data will be available soon? Thanks. Any help would be highly appreciated. ![1664522709309](https://user-images.githubusercontent.com/89521673/193214784-0e20b912-da63-44a7-ac26-75ebe5c31ac4.png)

oh，when the ap is also ESP32s2, the phenomenon above-mentioned will decrease a lot of course. I just wonder that if there is any method for the problem in which ESP served as sta and commodity WiFi as AP.

**Comment by dfx1822375** [comment]
> 

Hi, can we leave an email to exchange CSI related questions ?

**Comment by zhanzhaocheng** [comment]
@jiechen0809 If you want to be compatible with all router models, you can just take the LLTF field of csi, that is, the first 128 bytes of data

![image](https://user-images.githubusercontent.com/19528396/194704669-2e3770dc-1de1-4644-b994-77ea98a70277.png)

**Comment by jiechen0809** [comment]
> @jiechen0809 If you want to be compatible with all router models, you can just take the LLTF field of csi, that is, the first 128 bytes of data
> 
> ![image](https://user-images.githubusercontent.com/19528396/194704669-2e3770dc-1de1-4644-b994-77ea98a70277.png)

Thanks for your reply. What I mean is that even if I just take the LLTF field of csi, the types of csi packets still change frequently. For example, change from non-stbc to stbc or from long GI to short GI，which will lead to the large fluctuation of CSI data(include amplitude and phase). And this phenomenon cannot be solved by filtering simply, because the changes will  last for tens of seconds.

**Comment by zhanzhaocheng** [comment]
@jiechen0809 From the theoretical and practical test point of view, there is no problem you mentioned, and some customers also use it like this

LLTF is unaffected with or without HT-LTF, STBC-HT-LTF：
![image](https://user-images.githubusercontent.com/19528396/194705327-e36fca24-03cd-4d7b-84ed-fb0a8daf80fe.png)

**Comment by jiechen0809** [comment]
> @jiechen0809 From the theoretical and practical test point of view, there is no problem you mentioned, and some customers also use it like this
> 
> LLTF is unaffected with or without HT-LTF, STBC-HT-LTF： ![image](https://user-images.githubusercontent.com/19528396/194705327-e36fca24-03cd-4d7b-84ed-fb0a8daf80fe.png)

Thanks. I will have a try.

**Comment by jiechen0809** [comment]
> Another question, is it possible that the product which can get 1*2 tx-rx WiFi link CSI data will be available soon?
> Thanks. Any help would be highly appreciated.

How about the second question? Is it possible that the product which can get 1*2 tx-rx WiFi link CSI data will be available soon( 2 receive antennas)?
Thanks.

**Comment by dfx1822375** [comment]
> @zhanzhaocheng
> 
> How about the second question? Is it possible that the product which can get 1*2 tx-rx WiFi link CSI data will be available soon( 2 receive antennas)? Thanks.
dear @jiechen0809 ：
Hello, I have published some research on CSI signals, and now I want to collect the signals independently, 
can we communicate with each other about the problems?

**Comment by jiechen0809** [comment]
> > @zhanzhaocheng
> > How about the second question? Is it possible that the product which can get 1*2 tx-rx WiFi link CSI data will be available soon( 2 receive antennas)? Thanks.
> > dear @jiechen0809 ：
> > Hello, I have published some research on CSI signals, and now I want to collect the signals independently,
> > can we communicate with each other about the problems?

yes, sure.

**Comment by dfx1822375** [comment]
> > > @zhanzhaocheng
> > > How about the second question? Is it possible that the product which can get 1*2 tx-rx WiFi link CSI data will be available soon( 2 receive antennas)? Thanks.
> > > dear @jiechen0809 ：
> > > Hello, I have published some research on CSI signals, and now I want to collect the signals independently,
> > > can we communicate with each other about the problems?
> 
> yes, sure.

Thanks，can you give me your email or other contact information?

**Comment by jiechen0809** [comment]
> > > > @zhanzhaocheng
> > > > How about the second question? Is it possible that the product which can get 1*2 tx-rx WiFi link CSI data will be available soon( 2 receive antennas)? Thanks.
> > > > dear @jiechen0809 ：
> > > > Hello, I have published some research on CSI signals, and now I want to collect the signals independently,
> > > > can we communicate with each other about the problems?
> > 
> > 
> > yes, sure.
> 
> Thanks，can you give me your email or other contact information?

894901552@qq.com

**Comment by zhanzhaocheng** [comment]
> @zhanzhaocheng
> 
> How about the second question? Is it possible that the product which can get 1*2 tx-rx WiFi link CSI data will be available soon( 2 receive antennas)? Thanks.

The chip supporting 1*2 Tt-rx is not currently planned, but next year will mass-produce [ESP32-C5](https://www.espressif.com/en/news/ESP32-C5) which supports Wi-Fi 6 and 5.8G, can get more sub-carriers and better performance

**Comment by zhanzhaocheng** [comment]
> > > > @zhanzhaocheng
> > > > How about the second question? Is it possible that the product which can get 1*2 tx-rx WiFi link CSI data will be available soon( 2 receive antennas)? Thanks.
> > > > dear @jiechen0809 ：
> > > > Hello, I have published some research on CSI signals, and now I want to collect the signals independently,
> > > > can we communicate with each other about the problems?
> > 
> > 
> > yes, sure.
> 
> Thanks，can you give me your email or other contact information?

If you have a specific commercial project in progress, you can submit your needs [here](https://www.espressif.com/en/contact-us/technical-inquiries), and there will be specialized technical staff to connect with you

**Comment by jiechen0809** [comment]
> If you have a specific commercial project in progress, you can submit your needs [here](https://www.espressif.com/en/contact-us/technical-inquiries), and there will be specialized technical staff to connect with you

Thanks for your reply. If people want to have a wide and deployable application based on ESP series, there should acquire the  correct phase information of CSI.

**Comment by zhanzhaocheng** [comment]
Hello, @jiechen0809 

Closing this issue, feel free to reopen with more updates. Thanks.
