### ISSUE TITLE
Detect any Human Presence Using Two Esp32s

### ISSUE THREAD

**Issue by Gowtham-Gorajana** [espressif/esp-csi#77]
Can you please provide a detailed explanation on how to use the csi data to detect the human presence between the transmitter and the receiver. How we should send the data and set up the equpment and all.
research papers and video links would be helpful
Thanks

**Comment by zhanzhaocheng** [comment]
You can try this [example](https://github.com/espressif/esp-csi/tree/master/examples/console_test#esp-csi-console_test)

**Comment by Gowtham-Gorajana** [comment]
I am just new to this field and after extracting the CSI data how can we detect the presence of the humans graphically like it should give a spike when ever it detects a human ,etc...

**Comment by Gowtham-Gorajana** [comment]
what do we have to do to establish a connection between the two esp32s 
how can we transfer the data between the two

**Comment by zhanzhaocheng** [comment]
Hello, @Gowtham-Gorajana 

Closing this issue, feel free to reopen with more updates. Thanks.

**Comment by Asafe33** [comment]
@zhanzhaocheng this link is unreachable
