### ISSUE TITLE
abort() was called at PC 0x4015d702 on core 0

### ISSUE THREAD

**Issue by gc-night** [espressif/esp-csi#79]
Hello, I connect router to test console_test example. After i click train_start, abort() was called at PC 0x4015d702 on core 0    
Backtrace:0x40081d02:0x3fff45a00x40088e05:0x3fff45c0 0x4008f922:0x3fff45e0 0x4015d702:0x3fff4650 0x401435c7:0x3fff4670 0x401431ce:0x3fff4690 0x400da264:0x3fff46b0 0x400e332d:0x3fff46d0 0x400e355b:0x3fff4730 0x400d9b3f:0x3fff48d0 
ELF file SHA256: 6f4781e2dcc2e1ce

    then i use gdb for check the problem:
    (gdb) list *0x400d9b3f
0x400d9b3f is in csi_data_handle_task (/Users/zhanzhaocheng/project/esp-csi/esp-csi_release/esp-csi/examples/console_test/components/esp-csi/src/esp_radar.c:413).
408     /Users/zhanzhaocheng/project/esp-csi/esp-csi_release/esp-csi/examples/console_test/components/esp-csi/src/esp_radar.c: No such file or directory.

**Comment by zhanzhaocheng** [comment]
Thank you very much for finding this problem, this problem has now been fixed, and it will be updated to GitHub synchronously in the past two days

**Comment by zhanzhaocheng** [comment]
@gc-night This bug has been fixed and updated to github, please verify it after the update, if there are still problems, you are very welcome to ask

**Comment by zhanzhaocheng** [comment]
Hello, @gc-night 

Closing this issue, feel free to reopen with more updates. Thanks.
