### ISSUE TITLE
Resolve thid Gdb Error (AEGHB-219)

### ISSUE THREAD

**Issue by Gowtham-Gorajana** [espressif/esp-csi#80]
![image](https://user-images.githubusercontent.com/115892851/199692767-e436adb9-cc0f-4186-9918-c6974e5532d6.png)

**Comment by zhanzhaocheng** [comment]
@Gowtham-Gorajana  Sorry no one got back to you earlier.

Does this problem still exist, and can normal log information be received through other serial ports?

**Comment by zhanzhaocheng** [comment]
Hello, @Gowtham-Gorajana 

Closing this issue, feel free to reopen with more updates. Thanks.
