### ISSUE TITLE
Consultation on obtaining and storing CSI of multiple ESP32 anchor nodes at the same time

### ISSUE THREAD

**Issue by Sunlu2333** [espressif/esp-csi#81]
I'm trying to reproduce the experimental configuration highlighted in the following paper.
![image](https://user-images.githubusercontent.com/62133140/200742494-01dc0bbf-1854-4eac-b303-6a717074a177.png)

Refer to the following [project](https://github.com/StevenMHernandez/ESP32-CSI-Tool), I have implemented the CSI acquisition of one sending and one receiving through the active_ Ap and active_ STA, as shown in the figure. 
![image](https://user-images.githubusercontent.com/62133140/200743481-85e635c7-daab-43ab-a0ff-9a937b1fb3d3.png)

However, when applying the passive subproject, I cannot obtain any information through the monitor.
![image](https://user-images.githubusercontent.com/62133140/200743540-1037394e-b1a4-429c-84d6-7da51065023b.png)

What I want to do is to implement an AP as the TX and multiple STAs as the RXs(anchor nodes）, and then one ESP32 listens to the CSIs in these links. How can I achieve this and store the CSI data as a csv file? What I have are multiple ESP32-WROOOM-32D boards and.

Thank you very much for your attention and help!

**Comment by zhanzhaocheng** [comment]
You can refer to [this document ](https://github.com/espressif/esp-csi/tree/master/examples/get-started#get-started-examples)to try

**Comment by Sunlu2333** [comment]
Thank you for your suggestions! But I have a new problem: When I use one ESP32 board as AP and two ESP32 boards as STAs, which ping the same AP at the same time, and the fourth ESP32 board is assigned to sniff mode, I can only receive CSI from AP, and the number of packets received is not stable (All four boards work in channel 4). In detail, I can occasionally receive CSI from two STA, but after a period of time, I can only receive CSI from AP. So does it mean ESP32 will randomly listen to packets from AP or STA when working in sniff mode? What if I only want to listen to CSI from STA?
![image](https://user-images.githubusercontent.com/62133140/201027811-d4b05be2-c6c7-4af6-ae1b-1f3e6ba04511.png)

**Comment by zhanzhaocheng** [comment]
You can use the mac address for filtering, If the received CSI data is not what you want, just discard it
