### ISSUE TITLE
esp32s2 烧录get-started项目后的蓝屏问题

### ISSUE THREAD

**Issue by Dahuia** [espressif/esp-csi#83]
esp32s2烧录get-started项目后 再用tool去把CSI数据可视化 会出现电脑蓝屏问题
Bug Check String: ATTEMPTED_SWITCH_FROM_DPC
Bug Check Code: 0x000000b8
Caused By Driver: ntoskrnl.exe

**Comment by zhanzhaocheng** [comment]
Please refer to the solution [here](https://support.microsoft.com/en-us/sbs/windows/troubleshoot-blue-screen-errors-5c62726c-6489-52da-a372-3f73142c14ad) to locate the problem
