### ISSUE TITLE
the algorithm of intrusion detection

### ISSUE THREAD

**Issue by xiaokangkang6** [espressif/esp-csi#85]
Hello, thank you very much for sharing. Could you please share the algorithm of intrusion detection? I see that the algorithm is encapsulated in the library. Or maybe can you can tell me some algorithm ideas. Thank you very much !

**Comment by zhanzhaocheng** [comment]
I am very sorry that the current algorithm is not open source, you can refer to:https://ieeexplore.ieee.org/search/searchresult.jsp?newsearch=true&queryText=WIFI%20CSI

**Comment by zhanzhaocheng** [comment]
Hello, @xiaokangkang6 

Closing this issue, feel free to reopen with more updates. Thanks.
