### ISSUE TITLE
get the value of AGC of RX (AEGHB-113)

### ISSUE THREAD

**Issue by jiechen0809** [espressif/esp-csi#87]
Hi, I have seen that you can set the value of agc of Rx.  Like this:
ESP_ERROR_CHECK (esp_wifi_init ( &cfg))
 ; extern esp_err_t rom_rx_gain_force （ int force_en，int force_value）；// force_value 
rom_rx_gain_force ( true , 79 ) ;

I wonder that how to get the value of AGC of rx when the rx gain is automatic . Thanks.

**Comment by kszlgithub** [comment]
Users have no way to get rx gain yet, but we will make it happen later.

**Comment by zhanzhaocheng** [comment]
Hello, @jiechen0809

Closing this issue, feel free to reopen with more updates. Thanks.
