### ISSUE TITLE
csi_send ssid and password (AEGHB-10)

### ISSUE THREAD

**Issue by vivekrtx** [espressif/esp-csi#88]
Is there an option to provide ssid and password for the csi_send project before flashing? Or, what is the ssid and password set as in csi_send project if it is hardcoded?
Problem details: I have two ESP32 at different locations for sending wifi and one esp32 for receiving. I need two SSID of esp32 for sending wifi to capture path effects from different directions. So I need to specifically know which esp32 I am connecting to from the receiver.

**Comment by zhanzhaocheng** [comment]
The example of csi_send uses esp-now to send packets, so it does not need to be connected to a router, you just need to let the example of csi_send and the receiving end be on the same channel

**Comment by vivekrtx** [comment]
How to selectively connect with one of the two esp32 where both are sending packets? Both are flashed with csi_send and are located at different places. I need to connect to one of them with another esp32 (3rd one) maybe flashed with console_test instead of csi_receive. So I need to assign both of them ssid's to know which one I connected to. How do I assign ssid and password to selectively connect to one of them?

**Comment by zhanzhaocheng** [comment]
csi_send uses a different mac address, and the recv end can be filtered by mac address：https://github.com/espressif/esp-csi/blob/master/examples/get-started/csi_send/main/app_main.c#L45

**Comment by vivekrtx** [comment]
Thank you

**Comment by zhanzhaocheng** [comment]
Hello, @vivekrtx 

Closing this issue, feel free to reopen with more updates. Thanks.
