### ISSUE TITLE
Help (AEGHB-11)

### ISSUE THREAD

**Issue by tiyuuu** [espressif/esp-csi#90]
Hi, If I use 2 esp32 , transmitter esp connected with powerbank, and receiver esp connected with laptop, so how can i flash transmitter esp? where will i get the port connection as it is not connected with laptop.
Thanks

**Comment by zhanzhaocheng** [comment]
@tiyuuu I don't quite understand what you mean, can you describe it in another way?

**Comment by xiangshang-kok** [comment]
you should flash `csi_send`at first,then connect the esp32 to powerbank,

**Comment by zhanzhaocheng** [comment]
Hello, @tiyuuu 

Closing this issue, feel free to reopen with more updates. Thanks.
