### ISSUE TITLE
understanding the CSI data (AEGHB-67)

### ISSUE THREAD

**Issue by olliec28** [espressif/esp-csi#94]
Can anyone tell me what one row of the CSI data represents is it 1 row = 1 packet of data or does one row = 1 second for example. I am just trying to understand the data in order to feed it into a relevant ML algorithm. If anyone could tell me what algorithms they used as Im struggling to identify suitable ML algorithms at the moment. Thanks

**Comment by zhanzhaocheng** [comment]
A line of CSI is generated for each packet of data received
There is no limit to the algorithm of machine learning, such as RNN, CNN, KNN, etc.

**Comment by olliec28** [comment]
> A line of CSI is generated for each packet of data received
> There is no limit to the algorithm of machine learning, such as RNN, CNN, KNN, etc.

Will there need to be any signal preprocessing beforehand or simply input the CSI data straight into a neural network?

**Comment by zhanzhaocheng** [comment]
You can preprocess the data through algorithms such as Kalman filtering and low-pass filtering to improve the accuracy of recognition

**Comment by olliec28** [comment]
do you know which part of the code implements the local timestamp?

**Comment by zhanzhaocheng** [comment]
@olliec28 Sorry no one got back to you earlier.

Each frame of CSI information returned by ESP32 contains a timestamp, you can find it in `wifi_csi_info_t>rx_ctrl>timestamp`
