### ISSUE TITLE
real and imaginary part (AEGHB-76)

### ISSUE THREAD

**Issue by olliec28** [espressif/esp-csi#95]
I was just reading that the CSI data comes in 2 bytes as real and imaginary. Can anyone give more detail on how the imaginary part is calculated and should the imaginary part be removed during data pre-processing so that only the real CSI data is being used?

**Comment by zhanzhaocheng** [comment]
Each channel frequency response of sub-carrier is recorded by two bytes of signed characters. The first one is imaginary part and the second one is real part.
refer to: https://github.com/espressif/esp-csi/issues/24

**Comment by olliec28** [comment]
I know that, that’s what I’ve just stated. But how is the imaginary part calculated?

**Comment by zhanzhaocheng** [comment]
I don't understand what you want to ask, can you describe it more clearly?

**Comment by olliec28** [comment]
I’m asking where has this imaginary part come from, is it an estimation or guess? Like how is it calculated?

**Comment by zhanzhaocheng** [comment]
This is generated at the physical layer. You can refer to [this paper](https://www.cs.wm.edu/~yma/files/WiFiSensing_YongsenMa_authorversion.pdf) for the specific generation process.

**Comment by zhanzhaocheng** [comment]
Hello, @olliec28 

Closing this issue, feel free to reopen with more updates. Thanks.
