### ISSUE TITLE
Discussion board (AEGHB-83)

### ISSUE THREAD

**Issue by mars3142** [espressif/esp-csi#96]
You should open a discussion board (https://docs.github.com/de/discussions) within this github project. Right now the issues section is more a "can I get help" board.

**Comment by MacChu0315-Espressif** [comment]
Thank you very much for your suggestion! We have created a [discussion board](https://github.com/espressif/esp-csi/discussions) aimed at fostering further development and communication of the project. We warmly welcome everyone to post their future questions and discussions in the board, as it will facilitate focused discussions and the sharing of ideas. Once again, we appreciate your suggestion and look forward to engaging in deeper discussions with you there!
