### ISSUE TITLE
use it in older idf (AEGHB-84)

### ISSUE THREAD

**Issue by AlessandroCollina** [espressif/esp-csi#97]
Hi,

I'm trying to use it in an old project (idf 3.3).
I saw that the it's depend on the 4.4 version but i tried anyway :)

when I link the libesp-csi.a I have many errors like:

 invalid XTENSA reloc number: 58

The only soluction is adapt my old project on idf 4.4 or can I try some other soluction?

Thank and congratulations for the project, it works very well

Sandro

**Comment by MacChu0315-Espressif** [comment]
Basic functions about CSI is available on the idf-v3.3, while the algrithums we use base on idf-v4.4. 
So if you want to run the console_test, adapt your idf to v4.4 please.

**Comment by zhanzhaocheng** [comment]
Hello, @AlessandroCollina 

Closing this issue, feel free to reopen with more updates. Thanks.
