### ISSUE TITLE
Can't connect to my SOHO WiFi router using console test GUI  (AEGHB-104)

### ISSUE THREAD

**Issue by feliperj81** [espressif/esp-csi#98]
Hello!

First of all, I would like to congratulate you for the excellent work you have been doing on the project.

I'm trying to use the ep-csi API for the first time. I am using an ESP32 HELTEC (MCU ESP32-D0)

I followed what's is described on esp-csi console_test README.md, but I can't connect the ESP32 to my SOHO WiFi Router.

I also tryed this solution: https://github.com/espressif/esp-csi/issues/91

But no success.

I put the ssid and password on console_test GUI and I click on the CONNECT button but nothing happens.

Any suggestions?

**Comment by MacChu0315-Espressif** [comment]
We didn't recurrent your issue when using a ESP32 borad and a common router. Feels like that you provided too few information, try #101 first or provide more detailed info like LOG?

**Comment by zhanzhaocheng** [comment]
Hello, @feliperj81 

Closing this issue, feel free to reopen with more updates. Thanks.
